// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 案件参照履歴
/// </summary>
[Table("anken_sansyou_rirekis")]
public partial class AnkenSansyouRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 案件ID
    /// </summary>
    [Column("anken_id")]
    public long AnkenId { get; set; }

    /// <summary>
    /// 参照時間
    /// </summary>
    [Column("sansyou_time", TypeName = "timestamp without time zone")]
    public DateTime SansyouTime { get; set; }

    [ForeignKey("AnkenId")]
    [InverseProperty("AnkenSansyouRirekis")]
    public virtual Anken Anken { get; set; } = null!;

    [ForeignKey("SyainBaseId")]
    [InverseProperty("AnkenSansyouRirekis")]
    public virtual SyainBasis SyainBase { get; set; } = null!;
}