// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 案件
/// </summary>
[Table("ankens")]
public partial class Anken
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 案件名称
    /// </summary>
    [Column("name")]
    [StringLength(128)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 案件内容
    /// </summary>
    [Column("naiyou")]
    [StringLength(2000)]
    public string? Naiyou { get; set; }

    /// <summary>
    /// 顧客会社ID
    /// </summary>
    [Column("kokyaku_kaisya_id")]
    public long? KokyakuKaisyaId { get; set; }

    /// <summary>
    /// KINGS受注ID
    /// </summary>
    [Column("kings_juchu_id")]
    public long? KingsJuchuId { get; set; }

    /// <summary>
    /// 受注種類ID
    /// </summary>
    [Column("jyutyu_syurui_id")]
    public long? JyutyuSyuruiId { get; set; }

    /// <summary>
    /// 社員BaseID（責任者）
    /// </summary>
    [Column("syain_base_id")]
    public long? SyainBaseId { get; set; }

    /// <summary>
    /// 検索用案件名称
    /// </summary>
    [Column("search_name")]
    [StringLength(128)]
    public string SearchName { get; set; } = null!;

    [InverseProperty("Anken")]
    public virtual ICollection<AnkenSansyouRireki> AnkenSansyouRirekis { get; set; } = new List<AnkenSansyouRireki>();

    [ForeignKey("JyutyuSyuruiId")]
    [InverseProperty("Ankens")]
    public virtual JyutyuSyurui? JyutyuSyurui { get; set; }

    [ForeignKey("KingsJuchuId")]
    [InverseProperty("Ankens")]
    public virtual KingsJuchu? KingsJuchu { get; set; }

    [ForeignKey("KokyakuKaisyaId")]
    [InverseProperty("Ankens")]
    public virtual KokyakuKaisha? KokyakuKaisya { get; set; }

    [InverseProperty("Ankens")]
    public virtual ICollection<NippouAnken> NippouAnkens { get; set; } = new List<NippouAnken>();

    [ForeignKey("SyainBaseId")]
    [InverseProperty("Ankens")]
    public virtual SyainBasis? SyainBase { get; set; }
}