// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// アプリConfig
/// </summary>
[Table("application_configs")]
public partial class ApplicationConfig
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 日報停止日
    /// </summary>
    [Column("nippo_stop_date")]
    public DateOnly NippoStopDate { get; set; }

    /// <summary>
    /// MSテナントID
    /// </summary>
    [Column("ms_tenant_id")]
    [StringLength(256)]
    public string MsTenantId { get; set; } = null!;

    /// <summary>
    /// MSクライアントID
    /// </summary>
    [Column("ms_client_id")]
    [StringLength(256)]
    public string MsClientId { get; set; } = null!;

    /// <summary>
    /// MSクライアントシークレット
    /// </summary>
    [Column("ms_client_secret")]
    [StringLength(256)]
    public string MsClientSecret { get; set; } = null!;

    /// <summary>
    /// SMTPユーザ
    /// </summary>
    [Column("smtp_user")]
    [StringLength(256)]
    public string SmtpUser { get; set; } = null!;

    /// <summary>
    /// SMTPパスワード
    /// </summary>
    [Column("smtp_password")]
    [StringLength(256)]
    public string SmtpPassword { get; set; } = null!;
}