// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 部門プロセス
/// </summary>
[Table("bumon_process")]
public partial class BumonProcess
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 部署BaseID
    /// </summary>
    [Column("busyo_base_id")]
    public long BusyoBaseId { get; set; }

    /// <summary>
    /// コード
    /// </summary>
    [Column("code")]
    [StringLength(2)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 名称
    /// </summary>
    [Column("name")]
    [StringLength(10)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 親ID
    /// </summary>
    [Column("oya_id")]
    public long? OyaId { get; set; }

    /// <summary>
    /// 会社プロセスID
    /// </summary>
    [Column("kaisya_process_id")]
    public long? KaisyaProcessId { get; set; }

    /// <summary>
    /// 削除フラグ
    /// </summary>
    [Column("deleted")]
    public bool Deleted { get; set; }

    [ForeignKey("BusyoBaseId")]
    [InverseProperty("BumonProcesses")]
    public virtual BusyoBasis BusyoBase { get; set; } = null!;

    [InverseProperty("Oya")]
    public virtual ICollection<BumonProcess> InverseOya { get; set; } = new List<BumonProcess>();

    [ForeignKey("KaisyaProcessId")]
    [InverseProperty("BumonProcesses")]
    public virtual KaisyaProcess? KaisyaProcess { get; set; }

    [InverseProperty("BumonProcess")]
    public virtual ICollection<NippouAnken> NippouAnkens { get; set; } = new List<NippouAnken>();

    [ForeignKey("OyaId")]
    [InverseProperty("InverseOya")]
    public virtual BumonProcess? Oya { get; set; }
}