// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 部署マスタ
/// </summary>
[Table("busyos")]
public partial class Busyo
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 部署番号
    /// </summary>
    [Column("code")]
    [StringLength(3)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 部署名称
    /// </summary>
    [Column("name")]
    [StringLength(32)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 部署カナ名称
    /// </summary>
    [Column("kana_name")]
    [StringLength(64)]
    public string KanaName { get; set; } = null!;

    /// <summary>
    /// 親部署番号
    /// </summary>
    [Column("oya_code")]
    [StringLength(3)]
    public string OyaCode { get; set; } = null!;

    /// <summary>
    /// 有効開始日
    /// </summary>
    [Column("start_ymd")]
    public DateOnly StartYmd { get; set; }

    /// <summary>
    /// 有効終了日
    /// </summary>
    [Column("end_ymd")]
    public DateOnly EndYmd { get; set; }

    /// <summary>
    /// 並び順序
    /// </summary>
    [Column("jyunjyo")]
    public short Jyunjyo { get; set; }

    /// <summary>
    /// 箇所コード（精算システム上の処理単位）
    /// </summary>
    [Column("kasyo_code")]
    [StringLength(2)]
    public string KasyoCode { get; set; } = null!;

    /// <summary>
    /// 会計コード（日報システム上での部署コード）
    /// </summary>
    [Column("kaikei_code")]
    [StringLength(3)]
    public string KaikeiCode { get; set; } = null!;

    /// <summary>
    /// 経理コード（仕訳生成時の会計単位）
    /// </summary>
    [Column("keiri_code")]
    [StringLength(2)]
    public string? KeiriCode { get; set; }

    /// <summary>
    /// アクティブフラグ
    /// </summary>
    [Column("is_active")]
    public bool IsActive { get; set; }

    /// <summary>
    /// 略称
    /// </summary>
    [Column("ryakusyou")]
    [StringLength(10)]
    public string? Ryakusyou { get; set; }

    /// <summary>
    /// 部署BaseID
    /// </summary>
    [Column("busyo_base_id")]
    public long BusyoBaseId { get; set; }

    /// <summary>
    /// 親ID
    /// </summary>
    [Column("oya_id")]
    public long? OyaId { get; set; }

    /// <summary>
    /// 承認部署ID
    /// </summary>
    [Column("shonin_busyo_id")]
    public long? ShoninBusyoId { get; set; }

    [ForeignKey("BusyoBaseId")]
    [InverseProperty("Busyos")]
    public virtual BusyoBasis BusyoBase { get; set; } = null!;

    [InverseProperty("Oya")]
    public virtual ICollection<Busyo> InverseOya { get; set; } = new List<Busyo>();

    [InverseProperty("ShoninBusyo")]
    public virtual ICollection<Busyo> InverseShoninBusyo { get; set; } = new List<Busyo>();

    [InverseProperty("Busyo")]
    public virtual ICollection<KingsJuchu> KingsJuchus { get; set; } = new List<KingsJuchu>();

    [ForeignKey("OyaId")]
    [InverseProperty("InverseOya")]
    public virtual Busyo? Oya { get; set; }

    [ForeignKey("ShoninBusyoId")]
    [InverseProperty("InverseShoninBusyo")]
    public virtual Busyo? ShoninBusyo { get; set; }

    [InverseProperty("Busyo")]
    public virtual ICollection<Syain> Syains { get; set; } = new List<Syain>();
}