// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 部署BASEマスタ
/// </summary>
[Table("busyo_bases")]
public partial class BusyoBasis
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 名前
    /// </summary>
    [Column("name")]
    [StringLength(100)]
    public string? Name { get; set; }

    /// <summary>
    /// 部門長_ID
    /// </summary>
    [Column("bumoncyo_id")]
    public long? BumoncyoId { get; set; }

    [InverseProperty("BusyoBase")]
    public virtual ICollection<BumonProcess> BumonProcesses { get; set; } = new List<BumonProcess>();

    [ForeignKey("BumoncyoId")]
    [InverseProperty("BusyoBases")]
    public virtual SyainBasis? Bumoncyo { get; set; }

    [InverseProperty("BusyoBase")]
    public virtual ICollection<Busyo> Busyos { get; set; } = new List<Busyo>();
}