// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 連続勤務
/// </summary>
[Table("continuous_works")]
public partial class ContinuousWork
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 日時
    /// </summary>
    [Column("date", TypeName = "timestamp(6) without time zone")]
    public DateTime Date { get; set; }

    /// <summary>
    /// 連続勤務日数
    /// </summary>
    [Column("working_day")]
    public int WorkingDay { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("ContinuousWorks")]
    public virtual Syain Syain { get; set; } = null!;
}