// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 代理入力履歴
/// </summary>
[Table("dairi_nyuryoku_rirekis")]
public partial class DairiNyuryokuRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 代理入力社員ID
    /// </summary>
    [Column("dairi_nyuryoku_syain_id")]
    public long DairiNyuryokuSyainId { get; set; }

    /// <summary>
    /// 代理入力日時
    /// </summary>
    [Column("dairi_nyuryoku_time", TypeName = "timestamp without time zone")]
    public DateTime DairiNyuryokuTime { get; set; }

    /// <summary>
    /// 日報実績ID
    /// </summary>
    [Column("nippou_id")]
    public long NippouId { get; set; }

    /// <summary>
    /// 無効フラグ
    /// </summary>
    [Column("invalid")]
    public bool Invalid { get; set; }

    [ForeignKey("DairiNyuryokuSyainId")]
    [InverseProperty("DairiNyuryokuRirekis")]
    public virtual Syain DairiNyuryokuSyain { get; set; } = null!;

    [ForeignKey("NippouId")]
    [InverseProperty("DairiNyuryokuRirekis")]
    public virtual Nippou Nippou { get; set; } = null!;
}