// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 振替休暇残
/// </summary>
[Table("furikyuu_zans")]
public partial class FurikyuuZan
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 休日出勤年月日
    /// </summary>
    [Column("kyuujitsu_syukkin_ymd")]
    public DateOnly KyuujitsuSyukkinYmd { get; set; }

    /// <summary>
    /// 代休期限年月日
    /// </summary>
    [Column("daikyuu_kigen_ymd")]
    public DateOnly DaikyuuKigenYmd { get; set; }

    /// <summary>
    /// 取得年月日1
    /// </summary>
    [Column("syutoku_ymd1")]
    public DateOnly? SyutokuYmd1 { get; set; }

    /// <summary>
    /// 取得年月日2
    /// </summary>
    [Column("syutoku_ymd2")]
    public DateOnly? SyutokuYmd2 { get; set; }

    /// <summary>
    /// 1日フラグ
    /// </summary>
    [Column("is_one_day")]
    public bool IsOneDay { get; set; }

    /// <summary>
    /// 振休取得予定日
    /// </summary>
    [Column("syutoku_yotei_ymd")]
    public DateOnly? SyutokuYoteiYmd { get; set; }

    [InverseProperty("SyoukaFurikyuuZan")]
    public virtual ICollection<KyuukaKanri> KyuukaKanris { get; set; } = new List<KyuukaKanri>();

    [ForeignKey("SyainId")]
    [InverseProperty("FurikyuuZans")]
    public virtual Syain Syain { get; set; } = null!;
}