// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 業務タイプ
/// </summary>
[Table("gyoumu_types")]
public partial class GyoumuType
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 業務種別名称
    /// </summary>
    [Column("name")]
    [StringLength(96)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 表示順序
    /// </summary>
    [Column("jyunjyo")]
    public short Jyunjyo { get; set; }

    /// <summary>
    /// 削除フラグ
    /// </summary>
    [Column("deleted")]
    public bool Deleted { get; set; }

    [InverseProperty("GyoumuType")]
    public virtual ICollection<Syain> Syains { get; set; } = new List<Syain>();
}