// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 業種マスタ
/// </summary>
[Table("gyousyus")]
public partial class Gyousyu
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 業種コード
    /// </summary>
    [Column("code")]
    [StringLength(3)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 業種名称
    /// </summary>
    [Column("name")]
    [StringLength(32)]
    public string Name { get; set; } = null!;

    [InverseProperty("Gyousyu")]
    public virtual ICollection<KokyakuKaisha> KokyakuKaishas { get; set; } = new List<KokyakuKaisha>();
}