// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 実績確定締め日
/// </summary>
[Table("jisseki_kakutei_simebis")]
public partial class JissekiKakuteiSimebi
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 確定期限
    /// </summary>
    [Column("kakutei_kigen_ymd")]
    public DateOnly KakuteiKigenYmd { get; set; }

    [InverseProperty("JissekiKakuteiSimebi")]
    public virtual ICollection<MikakuteiTsuchiRireki> MikakuteiTsuchiRirekis { get; set; } = new List<MikakuteiTsuchiRireki>();
}