// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 受注種類
/// </summary>
[Table("jyutyu_syuruis")]
public partial class JyutyuSyurui
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 受注種類コード
    /// </summary>
    [Column("code")]
    [StringLength(3)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 受注種類名称
    /// </summary>
    [Column("name")]
    [StringLength(32)]
    public string Name { get; set; } = null!;

    [InverseProperty("JyutyuSyurui")]
    public virtual ICollection<Anken> Ankens { get; set; } = new List<Anken>();
}