// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 会社プロセス
/// </summary>
[Table("kaisya_process")]
public partial class KaisyaProcess
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// コード
    /// </summary>
    [Column("code")]
    [StringLength(2)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 名称
    /// </summary>
    [Column("name")]
    [StringLength(10)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 親ID
    /// </summary>
    [Column("oya_id")]
    public long? OyaId { get; set; }

    /// <summary>
    /// 削除フラグ
    /// </summary>
    [Column("deleted")]
    public bool Deleted { get; set; }

    [InverseProperty("KaisyaProcess")]
    public virtual ICollection<BumonProcess> BumonProcesses { get; set; } = new List<BumonProcess>();

    [InverseProperty("Oya")]
    public virtual ICollection<KaisyaProcess> InverseOya { get; set; } = new List<KaisyaProcess>();

    [ForeignKey("OyaId")]
    [InverseProperty("InverseOya")]
    public virtual KaisyaProcess? Oya { get; set; }
}