// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// KINGS受注登録
/// </summary>
[Table("kings_juchus")]
public partial class KingsJuchu
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 受注日
    /// </summary>
    [Column("juc_ymd")]
    public DateOnly JucYmd { get; set; }

    /// <summary>
    /// 受注登録日
    /// </summary>
    [Column("ent_ymd")]
    public DateOnly EntYmd { get; set; }

    /// <summary>
    /// 契約先
    /// </summary>
    [Column("kei_nm")]
    [StringLength(128)]
    public string? KeiNm { get; set; }

    /// <summary>
    /// 契約先カナ
    /// </summary>
    [Column("kei_kn")]
    [StringLength(128)]
    public string? KeiKn { get; set; }

    /// <summary>
    /// 受注先
    /// </summary>
    [Column("juc_nm")]
    [StringLength(128)]
    public string? JucNm { get; set; }

    /// <summary>
    /// 受注先カナ
    /// </summary>
    [Column("juc_kn")]
    [StringLength(128)]
    public string? JucKn { get; set; }

    /// <summary>
    /// 件名
    /// </summary>
    [Column("bukken")]
    [StringLength(256)]
    public string Bukken { get; set; } = null!;

    /// <summary>
    /// 送り元部署コード
    /// </summary>
    [Column("iri_bus_cd")]
    [StringLength(3)]
    public string? IriBusCd { get; set; }

    /// <summary>
    /// 受注金額
    /// </summary>
    [Column("juc_kin")]
    public long JucKin { get; set; }

    /// <summary>
    /// 送り担当者コード
    /// </summary>
    [Column("okr_tan_cd1")]
    [StringLength(5)]
    public string? OkrTanCd1 { get; set; }

    /// <summary>
    /// 送り担当者氏名
    /// </summary>
    [Column("okr_tan_nm1")]
    [StringLength(64)]
    public string? OkrTanNm1 { get; set; }

    /// <summary>
    /// 受け担当者コード
    /// </summary>
    [Column("uke_tan_cd1")]
    [StringLength(5)]
    public string? UkeTanCd1 { get; set; }

    /// <summary>
    /// 受け担当者氏名
    /// </summary>
    [Column("uke_tan_nm1")]
    [StringLength(64)]
    public string? UkeTanNm1 { get; set; }

    /// <summary>
    /// 着工日
    /// </summary>
    [Column("cha_ymd")]
    public DateOnly ChaYmd { get; set; }

    /// <summary>
    /// 納期施工
    /// </summary>
    [Column("nsy_ymd")]
    public DateOnly? NsyYmd { get; set; }

    /// <summary>
    /// 売上計画日
    /// </summary>
    [Column("kur_ymd")]
    public DateOnly? KurYmd { get; set; }

    /// <summary>
    /// 入金計画日
    /// </summary>
    [Column("kny_ymd")]
    public DateOnly? KnyYmd { get; set; }

    /// <summary>
    /// 備考
    /// </summary>
    [Column("biko")]
    [StringLength(1024)]
    public string? Biko { get; set; }

    /// <summary>
    /// 受注種類コード
    /// </summary>
    [Column("jsri_cd")]
    [StringLength(3)]
    public string? JsriCd { get; set; }

    /// <summary>
    /// 受注会社コード
    /// </summary>
    [Column("juc_cd")]
    [StringLength(7)]
    public string? JucCd { get; set; }

    /// <summary>
    /// プロジェクト番号
    /// </summary>
    [Column("project_no")]
    [StringLength(12)]
    public string ProjectNo { get; set; } = null!;

    /// <summary>
    /// 受注番号
    /// </summary>
    [Column("juchuu_no")]
    [StringLength(12)]
    public string? JuchuuNo { get; set; }

    /// <summary>
    /// 受注行番号
    /// </summary>
    [Column("juchuu_gyo_no")]
    public short? JuchuuGyoNo { get; set; }

    /// <summary>
    /// 契約状態区分名
    /// </summary>
    [Column("keiyaku_joutai_kbn_name")]
    [StringLength(40)]
    public string? KeiyakuJoutaiKbnName { get; set; }

    /// <summary>
    /// 施工部門コード
    /// </summary>
    [Column("sekou_bumon_cd")]
    [StringLength(3)]
    public string SekouBumonCd { get; set; } = null!;

    /// <summary>
    /// 費用種別コード
    /// </summary>
    [Column("hiyou_shubetu_cd")]
    public short HiyouShubetuCd { get; set; }

    /// <summary>
    /// 費用種別名
    /// </summary>
    [Column("hiyou_shubetu_cd_name")]
    [StringLength(80)]
    public string HiyouShubetuCdName { get; set; } = null!;

    /// <summary>
    /// 原価凍結フラグ
    /// </summary>
    [Column("is_genka_toketu")]
    public bool IsGenkaToketu { get; set; }

    /// <summary>
    /// 原価凍結日
    /// </summary>
    [Column("toketu_ymd")]
    public DateOnly? ToketuYmd { get; set; }

    /// <summary>
    /// 年度
    /// </summary>
    [Column("nendo")]
    public short Nendo { get; set; }

    /// <summary>
    /// 商品名
    /// </summary>
    [Column("shouhin_name")]
    [StringLength(200)]
    public string? ShouhinName { get; set; }

    /// <summary>
    /// 部署ID（施工部門）
    /// </summary>
    [Column("busyo_id")]
    public long BusyoId { get; set; }

    /// <summary>
    /// 検索用契約先
    /// </summary>
    [Column("search_kei_nm")]
    [StringLength(128)]
    public string? SearchKeiNm { get; set; }

    /// <summary>
    /// 検索用契約先カナ
    /// </summary>
    [Column("search_kei_kn")]
    [StringLength(128)]
    public string? SearchKeiKn { get; set; }

    /// <summary>
    /// 検索用受注先
    /// </summary>
    [Column("search_juc_nm")]
    [StringLength(128)]
    public string? SearchJucNm { get; set; }

    /// <summary>
    /// 検索用受注先カナ
    /// </summary>
    [Column("search_juc_kn")]
    [StringLength(128)]
    public string? SearchJucKn { get; set; }

    /// <summary>
    /// 検索用件名
    /// </summary>
    [Column("search_bukken")]
    [StringLength(256)]
    public string SearchBukken { get; set; } = null!;

    [InverseProperty("KingsJuchu")]
    public virtual ICollection<Anken> Ankens { get; set; } = new List<Anken>();

    [ForeignKey("BusyoId")]
    [InverseProperty("KingsJuchus")]
    public virtual Busyo Busyo { get; set; } = null!;

    [InverseProperty("KingsJuchu")]
    public virtual ICollection<KingsJuchuSansyouRireki> KingsJuchuSansyouRirekis { get; set; } = new List<KingsJuchuSansyouRireki>();
}