// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// KINGS受注参照履歴
/// </summary>
[Table("kings_juchu_sansyou_rirekis")]
public partial class KingsJuchuSansyouRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 参照時間
    /// </summary>
    [Column("sansyou_time", TypeName = "timestamp without time zone")]
    public DateTime SansyouTime { get; set; }

    /// <summary>
    /// KINGS受注ID
    /// </summary>
    [Column("kings_juchu_id")]
    public long KingsJuchuId { get; set; }

    [ForeignKey("KingsJuchuId")]
    [InverseProperty("KingsJuchuSansyouRirekis")]
    public virtual KingsJuchu KingsJuchu { get; set; } = null!;

    [ForeignKey("SyainBaseId")]
    [InverseProperty("KingsJuchuSansyouRirekis")]
    public virtual SyainBasis SyainBase { get; set; } = null!;
}