// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 勤怠属性
/// </summary>
[Table("kintai_zokuseis")]
public partial class KintaiZokusei
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Column("name")]
    [StringLength(64)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 制限時間:0は無制限
    /// </summary>
    [Column("seigen_time")]
    [Precision(5, 2)]
    public decimal SeigenTime { get; set; }

    /// <summary>
    /// みなしフラグ
    /// </summary>
    [Column("is_minashi")]
    public bool IsMinashi { get; set; }

    /// <summary>
    /// 最大限界時間:0は無制限
    /// </summary>
    [Column("max_limit_time")]
    [Precision(5, 2)]
    public decimal MaxLimitTime { get; set; }

    /// <summary>
    /// 残業制限時間累計期間3ヶ月フラグ
    /// </summary>
    [Column("is_overtime_limit_3m")]
    public bool IsOvertimeLimit3m { get; set; }

    [InverseProperty("KintaiZokusei")]
    public virtual ICollection<Syain> Syains { get; set; } = new List<Syain>();
}