// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 顧客会社
/// </summary>
[Table("kokyaku_kaishas")]
public partial class KokyakuKaisha
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 顧客コード
    /// </summary>
    [Column("code")]
    public int Code { get; set; }

    /// <summary>
    /// 顧客名称
    /// </summary>
    [Column("name")]
    [StringLength(64)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 顧客名カナ
    /// </summary>
    [Column("name_kana")]
    [StringLength(128)]
    public string NameKana { get; set; } = null!;

    /// <summary>
    /// 顧客名略称
    /// </summary>
    [Column("ryakusyou")]
    [StringLength(64)]
    public string Ryakusyou { get; set; } = null!;

    /// <summary>
    /// 郵便番号
    /// </summary>
    [Column("yuubin_bangou")]
    [StringLength(8)]
    public string? YuubinBangou { get; set; }

    /// <summary>
    /// 住所１
    /// </summary>
    [Column("jyuusyo1")]
    [StringLength(128)]
    public string? Jyuusyo1 { get; set; }

    /// <summary>
    /// 住所２
    /// </summary>
    [Column("jyuusyo2")]
    [StringLength(128)]
    public string? Jyuusyo2 { get; set; }

    /// <summary>
    /// TEL番号
    /// </summary>
    [Column("tel")]
    [StringLength(15)]
    public string? Tel { get; set; }

    /// <summary>
    /// FAX番号
    /// </summary>
    [Column("fax")]
    [StringLength(15)]
    public string? Fax { get; set; }

    /// <summary>
    /// 業種コード
    /// </summary>
    [Column("gyousyu_code")]
    [StringLength(3)]
    public string? GyousyuCode { get; set; }

    /// <summary>
    /// メモ
    /// </summary>
    [Column("memo")]
    [StringLength(2000)]
    public string? Memo { get; set; }

    /// <summary>
    /// URL
    /// </summary>
    [Column("url")]
    [StringLength(128)]
    public string? Url { get; set; }

    /// <summary>
    /// 紹介者コード
    /// </summary>
    [Column("syoukaisya_code")]
    public int? SyoukaisyaCode { get; set; }

    /// <summary>
    /// 紹介内容
    /// </summary>
    [Column("syoukai_naiyou")]
    [StringLength(2000)]
    public string? SyoukaiNaiyou { get; set; }

    /// <summary>
    /// 支店名称
    /// </summary>
    [Column("shiten")]
    [StringLength(64)]
    public string? Shiten { get; set; }

    /// <summary>
    /// 業種ID
    /// </summary>
    [Column("gyousyu_id")]
    public long? GyousyuId { get; set; }

    /// <summary>
    /// 社員BaseID（営業担当）
    /// </summary>
    [Column("eigyo_base_syain_id")]
    public long? EigyoBaseSyainId { get; set; }

    /// <summary>
    /// 社員BaseID（紹介担当）
    /// </summary>
    [Column("syokai_base_syain_id")]
    public long? SyokaiBaseSyainId { get; set; }

    /// <summary>
    /// 検索用顧客名称
    /// </summary>
    [Column("search_name")]
    [StringLength(64)]
    public string SearchName { get; set; } = null!;

    /// <summary>
    /// 検索用顧客名称カナ
    /// </summary>
    [Column("search_name_kana")]
    [StringLength(128)]
    public string SearchNameKana { get; set; } = null!;

    [InverseProperty("KokyakuKaisya")]
    public virtual ICollection<Anken> Ankens { get; set; } = new List<Anken>();

    [ForeignKey("EigyoBaseSyainId")]
    [InverseProperty("KokyakuKaishaEigyoBaseSyains")]
    public virtual SyainBasis? EigyoBaseSyain { get; set; }

    [ForeignKey("GyousyuId")]
    [InverseProperty("KokyakuKaishas")]
    public virtual Gyousyu? Gyousyu { get; set; }

    [InverseProperty("KokyakuKaisya")]
    public virtual ICollection<KokyakuKaisyaSansyouRireki> KokyakuKaisyaSansyouRirekis { get; set; } = new List<KokyakuKaisyaSansyouRireki>();

    [InverseProperty("KokyakuKaisya")]
    public virtual ICollection<NippouAnken> NippouAnkens { get; set; } = new List<NippouAnken>();

    [ForeignKey("SyokaiBaseSyainId")]
    [InverseProperty("KokyakuKaishaSyokaiBaseSyains")]
    public virtual SyainBasis? SyokaiBaseSyain { get; set; }
}