// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 顧客会社参照履歴
/// </summary>
[Table("kokyaku_kaisya_sansyou_rirekis")]
public partial class KokyakuKaisyaSansyouRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BASE_ID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 顧客会社_ID
    /// </summary>
    [Column("kokyaku_kaisya_id")]
    public long KokyakuKaisyaId { get; set; }

    /// <summary>
    /// 参照時間
    /// </summary>
    [Column("sansyou_time", TypeName = "timestamp without time zone")]
    public DateTime SansyouTime { get; set; }

    [ForeignKey("KokyakuKaisyaId")]
    [InverseProperty("KokyakuKaisyaSansyouRirekis")]
    public virtual KokyakuKaisha KokyakuKaisya { get; set; } = null!;

    [ForeignKey("SyainBaseId")]
    [InverseProperty("KokyakuKaisyaSansyouRirekis")]
    public virtual SyainBasis SyainBase { get; set; } = null!;
}