// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 休暇管理
/// </summary>
[Table("kyuuka_kanris")]
public partial class KyuukaKanri
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 休暇区分
    /// </summary>
    [Column("kyuuka_kubun")]
    [StringLength(2)]
    public string KyuukaKubun { get; set; } = null!;

    /// <summary>
    /// 対象年月日
    /// </summary>
    [Column("taisyou_ymd")]
    public DateOnly TaisyouYmd { get; set; }

    /// <summary>
    /// 振替休暇残ID
    /// </summary>
    [Column("syouka_furikyuu_zan_id")]
    public long? SyoukaFurikyuuZanId { get; set; }

    /// <summary>
    /// 補填労働時間
    /// </summary>
    [Column("hoten_rudou_jikan")]
    [Precision(6, 2)]
    public decimal? HotenRudouJikan { get; set; }

    /// <summary>
    /// 出勤区分ID1
    /// </summary>
    [Column("syukkin_kubun_id1")]
    public long? SyukkinKubunId1 { get; set; }

    /// <summary>
    /// 出勤区分ID2
    /// </summary>
    [Column("syukkin_kubun_id2")]
    public long? SyukkinKubunId2 { get; set; }

    [ForeignKey("SyainBaseId")]
    [InverseProperty("KyuukaKanris")]
    public virtual SyainBasis SyainBase { get; set; } = null!;

    [ForeignKey("SyoukaFurikyuuZanId")]
    [InverseProperty("KyuukaKanris")]
    public virtual FurikyuuZan? SyoukaFurikyuuZan { get; set; }

    [ForeignKey("SyukkinKubunId1")]
    [InverseProperty("KyuukaKanriSyukkinKubunId1Navigations")]
    public virtual SyukkinKubun? SyukkinKubunId1Navigation { get; set; }

    [ForeignKey("SyukkinKubunId2")]
    [InverseProperty("KyuukaKanriSyukkinKubunId2Navigations")]
    public virtual SyukkinKubun? SyukkinKubunId2Navigation { get; set; }
}