// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 送信内容
/// </summary>
[Table("message_contents")]
public partial class MessageContent
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 内容
    /// </summary>
    [Column("content")]
    public string Content { get; set; } = null!;

    /// <summary>
    /// 送信時刻
    /// </summary>
    [Column("send_datetime", TypeName = "timestamp without time zone")]
    public DateTime? SendDatetime { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("MessageContents")]
    public virtual Syain Syain { get; set; } = null!;
}