// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 未確定通知送信履歴
/// </summary>
[Table("mikakutei_tsuchi_rirekis")]
public partial class MikakuteiTsuchiRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 通知送信社員ID
    /// </summary>
    [Column("send_syain_base_id")]
    public long SendSyainBaseId { get; set; }

    /// <summary>
    /// 実績確定締め日ID
    /// </summary>
    [Column("jisseki_kakutei_simebi_id")]
    public long JissekiKakuteiSimebiId { get; set; }

    /// <summary>
    /// 通知送信日時
    /// </summary>
    [Column("tuuti_sousin_nitizi", TypeName = "timestamp without time zone")]
    public DateTime TuutiSousinNitizi { get; set; }

    /// <summary>
    /// 送信メッセージ
    /// </summary>
    [Column("send_message")]
    [StringLength(2000)]
    public string SendMessage { get; set; } = null!;

    [ForeignKey("JissekiKakuteiSimebiId")]
    [InverseProperty("MikakuteiTsuchiRirekis")]
    public virtual JissekiKakuteiSimebi JissekiKakuteiSimebi { get; set; } = null!;

    [ForeignKey("SendSyainBaseId")]
    [InverseProperty("MikakuteiTsuchiRirekis")]
    public virtual SyainBasis SendSyainBase { get; set; } = null!;

    [InverseProperty("MikakuteiTsuchiRireki")]
    public virtual ICollection<SyainTsuchiRirekiRel> SyainTsuchiRirekiRels { get; set; } = new List<SyainTsuchiRirekiRel>();
}