// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 日報予定
/// </summary>
[Table("nippou_yoteis")]
public partial class NippouYotei
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 予定年月日
    /// </summary>
    [Column("nippou_yotei_ymd")]
    public DateOnly NippouYoteiYmd { get; set; }

    /// <summary>
    /// 出勤フラグ
    /// </summary>
    [Column("worked")]
    public bool Worked { get; set; }

    /// <summary>
    /// 残業時間
    /// </summary>
    [Column("zangyou_jikan")]
    public short ZangyouJikan { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("NippouYoteis")]
    public virtual Syain Syain { get; set; } = null!;
}