// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 日報実績
/// </summary>
[Table("nippous")]
public partial class Nippou
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 実績年月日
    /// </summary>
    [Column("nippou_ymd")]
    public DateOnly NippouYmd { get; set; }

    /// <summary>
    /// 曜日
    /// </summary>
    [Column("youbi")]
    public short Youbi { get; set; }

    /// <summary>
    /// 出勤時間1
    /// </summary>
    [Column("syukkin_hm1")]
    public TimeOnly? SyukkinHm1 { get; set; }

    /// <summary>
    /// 退出時間1
    /// </summary>
    [Column("taisyutsu_hm1")]
    public TimeOnly? TaisyutsuHm1 { get; set; }

    /// <summary>
    /// 出勤時間2
    /// </summary>
    [Column("syukkin_hm2")]
    public TimeOnly? SyukkinHm2 { get; set; }

    /// <summary>
    /// 退出時間2
    /// </summary>
    [Column("taisyutsu_hm2")]
    public TimeOnly? TaisyutsuHm2 { get; set; }

    /// <summary>
    /// 出勤時間3
    /// </summary>
    [Column("syukkin_hm3")]
    public TimeOnly? SyukkinHm3 { get; set; }

    /// <summary>
    /// 退出時間3
    /// </summary>
    [Column("taisyutsu_hm3")]
    public TimeOnly? TaisyutsuHm3 { get; set; }

    /// <summary>
    /// 平日実働
    /// </summary>
    [Column("h_jitsudou")]
    [Precision(6, 2)]
    public decimal? HJitsudou { get; set; }

    /// <summary>
    /// 平日残業
    /// </summary>
    [Column("h_zangyo")]
    [Precision(6, 2)]
    public decimal? HZangyo { get; set; }

    /// <summary>
    /// 平日割増
    /// </summary>
    [Column("h_warimashi")]
    [Precision(6, 2)]
    public decimal? HWarimashi { get; set; }

    /// <summary>
    /// 平日深夜残業
    /// </summary>
    [Column("h_shinya_zangyo")]
    [Precision(6, 2)]
    public decimal? HShinyaZangyo { get; set; }

    /// <summary>
    /// 土祝祭日実働
    /// </summary>
    [Column("d_jitsudou")]
    [Precision(6, 2)]
    public decimal? DJitsudou { get; set; }

    /// <summary>
    /// 土祝祭日残業
    /// </summary>
    [Column("d_zangyo")]
    [Precision(6, 2)]
    public decimal? DZangyo { get; set; }

    /// <summary>
    /// 土祝祭日割増
    /// </summary>
    [Column("d_warimashi")]
    [Precision(6, 2)]
    public decimal? DWarimashi { get; set; }

    /// <summary>
    /// 土祝祭日深夜残業
    /// </summary>
    [Column("d_shinya_zangyo")]
    [Precision(6, 2)]
    public decimal? DShinyaZangyo { get; set; }

    /// <summary>
    /// 法定休日実働
    /// </summary>
    [Column("n_jitsudou")]
    [Precision(6, 2)]
    public decimal? NJitsudou { get; set; }

    /// <summary>
    /// 法定休日深夜
    /// </summary>
    [Column("n_shinya")]
    [Precision(6, 2)]
    public decimal? NShinya { get; set; }

    /// <summary>
    /// みなし対象外用残業
    /// </summary>
    [Column("total_zangyo")]
    [Precision(6, 2)]
    public decimal? TotalZangyo { get; set; }

    /// <summary>
    /// 連動済フラグ
    /// </summary>
    [Column("is_rendou_zumi")]
    public bool IsRendouZumi { get; set; }

    /// <summary>
    /// 連動年月日
    /// </summary>
    [Column("rendou_ymd")]
    public DateOnly? RendouYmd { get; set; }

    /// <summary>
    /// 確定年月日
    /// </summary>
    [Column("kakutei_ymd")]
    public DateOnly? KakuteiYmd { get; set; }

    /// <summary>
    /// 出勤区分ID1
    /// </summary>
    [Column("syukkin_kubun_id1")]
    public long SyukkinKubunId1 { get; set; }

    /// <summary>
    /// 出勤区分ID2
    /// </summary>
    [Column("syukkin_kubun_id2")]
    public long? SyukkinKubunId2 { get; set; }

    [InverseProperty("Nippou")]
    public virtual ICollection<DairiNyuryokuRireki> DairiNyuryokuRirekis { get; set; } = new List<DairiNyuryokuRireki>();

    [InverseProperty("Nippou")]
    public virtual ICollection<NippouAnken> NippouAnkens { get; set; } = new List<NippouAnken>();

    [ForeignKey("SyainId")]
    [InverseProperty("Nippous")]
    public virtual Syain Syain { get; set; } = null!;

    [ForeignKey("SyukkinKubunId1")]
    [InverseProperty("NippouSyukkinKubunId1Navigations")]
    public virtual SyukkinKubun SyukkinKubunId1Navigation { get; set; } = null!;

    [ForeignKey("SyukkinKubunId2")]
    [InverseProperty("NippouSyukkinKubunId2Navigations")]
    public virtual SyukkinKubun? SyukkinKubunId2Navigation { get; set; }
}