// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 日報実績⇔案件
/// </summary>
[Table("nippou_ankens")]
public partial class NippouAnken
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 日報実績ID
    /// </summary>
    [Column("nippou_id")]
    public long NippouId { get; set; }

    /// <summary>
    /// 案件_ID
    /// </summary>
    [Column("ankens_id")]
    public long AnkensId { get; set; }

    /// <summary>
    /// 顧客名
    /// </summary>
    [Column("kokyaku_name")]
    [StringLength(64)]
    public string KokyakuName { get; set; } = null!;

    /// <summary>
    /// 案件名
    /// </summary>
    [Column("anken_name")]
    [StringLength(128)]
    public string AnkenName { get; set; } = null!;

    /// <summary>
    /// 実績時間
    /// </summary>
    [Column("jisseki_jikan")]
    public short JissekiJikan { get; set; }

    /// <summary>
    /// 顧客会社ID
    /// </summary>
    [Column("kokyaku_kaisya_id")]
    public long KokyakuKaisyaId { get; set; }

    /// <summary>
    /// 部門プロセスID
    /// </summary>
    [Column("bumon_process_id")]
    public long? BumonProcessId { get; set; }

    /// <summary>
    /// 原価連携フラグ
    /// </summary>
    [Column("is_linked")]
    public bool IsLinked { get; set; }

    [ForeignKey("AnkensId")]
    [InverseProperty("NippouAnkens")]
    public virtual Anken Ankens { get; set; } = null!;

    [ForeignKey("BumonProcessId")]
    [InverseProperty("NippouAnkens")]
    public virtual BumonProcess? BumonProcess { get; set; }

    [ForeignKey("KokyakuKaisyaId")]
    [InverseProperty("NippouAnkens")]
    public virtual KokyakuKaisha KokyakuKaisya { get; set; } = null!;

    [ForeignKey("NippouId")]
    [InverseProperty("NippouAnkens")]
    public virtual Nippou Nippou { get; set; } = null!;
}