// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 残業時間アラート:旧warn_overtime_work
/// </summary>
[Table("overtime_alerts")]
public partial class OvertimeAlert
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// サービス実行履歴ID
    /// </summary>
    [Column("service_execute_history_id")]
    public long ServiceExecuteHistoryId { get; set; }

    /// <summary>
    /// 年月
    /// </summary>
    [Column("year_month")]
    [StringLength(6)]
    public string YearMonth { get; set; } = null!;

    [ForeignKey("ServiceExecuteHistoryId")]
    [InverseProperty("OvertimeAlerts")]
    public virtual ServiceExecuteHistory ServiceExecuteHistory { get; set; } = null!;

    [ForeignKey("SyainBaseId")]
    [InverseProperty("OvertimeAlerts")]
    public virtual Syain SyainBase { get; set; } = null!;
}