// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 残業超過制限
/// </summary>
[Table("overtime_excess_limits")]
public partial class OvertimeExcessLimit
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 無効年月
    /// </summary>
    [Column("disabled_ym")]
    public DateOnly DisabledYm { get; set; }

    [ForeignKey("SyainBaseId")]
    [InverseProperty("OvertimeExcessLimits")]
    public virtual SyainBasis SyainBase { get; set; } = null!;
}