// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// PCログ
/// </summary>
[Table("pc_logs")]
public partial class PcLog
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 日時
    /// </summary>
    [Column("datetime", TypeName = "timestamp without time zone")]
    public DateTime Datetime { get; set; }

    /// <summary>
    /// コンピューター名
    /// </summary>
    [Column("pc_name")]
    [StringLength(50)]
    public string PcName { get; set; } = null!;

    /// <summary>
    /// ログオンユーザ名
    /// </summary>
    [Column("user_name")]
    [StringLength(50)]
    public string? UserName { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long? SyainId { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("PcLogs")]
    public virtual Syain? Syain { get; set; }
}