// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 社員の顔写真データ（加工後のサムネイル）
/// </summary>
[Table("photo_after_process_tn_datas")]
public partial class PhotoAfterProcessTnData
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員写真ID
    /// </summary>
    [Column("syain_photo_id")]
    public long SyainPhotoId { get; set; }

    /// <summary>
    /// 写真
    /// </summary>
    [Column("photo")]
    public byte[] Photo { get; set; } = null!;

    [ForeignKey("SyainPhotoId")]
    [InverseProperty("PhotoAfterProcessTnData")]
    public virtual SyainPhoto SyainPhoto { get; set; } = null!;
}