// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// サービス実行履歴
/// </summary>
[Table("service_execute_histories")]
public partial class ServiceExecuteHistory
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 実行開始日時
    /// </summary>
    [Column("execute_datetime", TypeName = "timestamp without time zone")]
    public DateTime ExecuteDatetime { get; set; }

    /// <summary>
    /// 完了日時
    /// </summary>
    [Column("completed_datetime", TypeName = "timestamp without time zone")]
    public DateTime CompletedDatetime { get; set; }

    /// <summary>
    /// 内容
    /// </summary>
    [Column("content")]
    public string? Content { get; set; }

    [InverseProperty("ServiceExecuteHistory")]
    public virtual ICollection<OvertimeAlert> OvertimeAlerts { get; set; } = new List<OvertimeAlert>();

    [InverseProperty("ServiceExecuteHistory")]
    public virtual ICollection<UnpaidLeaveAlert> UnpaidLeaveAlerts { get; set; } = new List<UnpaidLeaveAlert>();
}