// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// サービス実行
/// </summary>
[Table("service_executes")]
public partial class ServiceExecute
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 稼働中?
    /// </summary>
    [Column("used")]
    public bool Used { get; set; }
}