// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 社員⇔未確定通知送信履歴
/// </summary>
[Table("syain_tsuchi_rireki_rels")]
public partial class SyainTsuchiRirekiRel
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 通知対象社員ID
    /// </summary>
    [Column("tsuchi_syain_base_id")]
    public long TsuchiSyainBaseId { get; set; }

    /// <summary>
    /// 未確定通知送信履歴ID
    /// </summary>
    [Column("mikakutei_tsuchi_rireki_id")]
    public long MikakuteiTsuchiRirekiId { get; set; }

    [ForeignKey("MikakuteiTsuchiRirekiId")]
    [InverseProperty("SyainTsuchiRirekiRels")]
    public virtual MikakuteiTsuchiRireki MikakuteiTsuchiRireki { get; set; } = null!;

    [ForeignKey("TsuchiSyainBaseId")]
    [InverseProperty("SyainTsuchiRirekiRels")]
    public virtual SyainBasis TsuchiSyainBase { get; set; } = null!;
}