// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 社員マスタ
/// </summary>
[Table("syains")]
public partial class Syain
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員番号
    /// </summary>
    [Column("code")]
    [StringLength(5)]
    public string Code { get; set; } = null!;

    /// <summary>
    /// 社員氏名
    /// </summary>
    [Column("name")]
    [StringLength(32)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 社員氏名カナ
    /// </summary>
    [Column("kana_name")]
    [StringLength(32)]
    public string KanaName { get; set; } = null!;

    /// <summary>
    /// 性別
    /// </summary>
    [Column("seibetsu")]
    [MaxLength(1)]
    public char Seibetsu { get; set; }

    /// <summary>
    /// 部署コード
    /// </summary>
    [Column("busyo_code")]
    [StringLength(3)]
    public string BusyoCode { get; set; } = null!;

    /// <summary>
    /// 職種コード
    /// </summary>
    [Column("syokusyu_code")]
    public int SyokusyuCode { get; set; }

    /// <summary>
    /// 職種分類コード
    /// </summary>
    [Column("syokusyu_bunrui_code")]
    public int SyokusyuBunruiCode { get; set; }

    /// <summary>
    /// 入社年月日
    /// </summary>
    [Column("nyuusya_ymd")]
    public DateOnly NyuusyaYmd { get; set; }

    /// <summary>
    /// 有効開始日
    /// </summary>
    [Column("start_ymd")]
    public DateOnly StartYmd { get; set; }

    /// <summary>
    /// 有効終了日
    /// </summary>
    [Column("end_ymd")]
    public DateOnly EndYmd { get; set; }

    /// <summary>
    /// 級職
    /// </summary>
    [Column("kyusyoku")]
    public short Kyusyoku { get; set; }

    /// <summary>
    /// KINGS所属
    /// </summary>
    [Column("kings_syozoku")]
    [StringLength(5)]
    public string KingsSyozoku { get; set; } = null!;

    /// <summary>
    /// 会社コード
    /// </summary>
    [Column("kaisya_code")]
    public short KaisyaCode { get; set; }

    /// <summary>
    /// 原価連動フラグ
    /// </summary>
    [Column("is_genka_rendou")]
    public bool IsGenkaRendou { get; set; }

    /// <summary>
    /// Ｅ－Ｍａｉｌアドレス
    /// </summary>
    [Column("e_mail")]
    [StringLength(50)]
    public string? EMail { get; set; }

    /// <summary>
    /// 携帯Ｍａｉｌアドレス
    /// </summary>
    [Column("keitai_mail")]
    [StringLength(50)]
    public string? KeitaiMail { get; set; }

    /// <summary>
    /// 並び順序
    /// </summary>
    [Column("jyunjyo")]
    public short Jyunjyo { get; set; }

    /// <summary>
    /// 退職フラグ
    /// </summary>
    [Column("retired")]
    public bool Retired { get; set; }

    /// <summary>
    /// 業務タイプID
    /// </summary>
    [Column("gyoumu_type_id")]
    public long? GyoumuTypeId { get; set; }

    /// <summary>
    /// 電話番号
    /// </summary>
    [Column("phone_number")]
    [StringLength(15)]
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 部署ID
    /// </summary>
    [Column("busyo_id")]
    public long BusyoId { get; set; }

    /// <summary>
    /// 勤怠属性ID
    /// </summary>
    [Column("kintai_zokusei_id")]
    public long KintaiZokuseiId { get; set; }

    /// <summary>
    /// ユーザーロールID
    /// </summary>
    [Column("user_role_id")]
    public long UserRoleId { get; set; }

    [ForeignKey("BusyoId")]
    [InverseProperty("Syains")]
    public virtual Busyo Busyo { get; set; } = null!;

    [InverseProperty("Syain")]
    public virtual ICollection<ContinuousWork> ContinuousWorks { get; set; } = new List<ContinuousWork>();

    [InverseProperty("DairiNyuryokuSyain")]
    public virtual ICollection<DairiNyuryokuRireki> DairiNyuryokuRirekis { get; set; } = new List<DairiNyuryokuRireki>();

    [InverseProperty("Syain")]
    public virtual ICollection<FurikyuuZan> FurikyuuZans { get; set; } = new List<FurikyuuZan>();

    [ForeignKey("GyoumuTypeId")]
    [InverseProperty("Syains")]
    public virtual GyoumuType? GyoumuType { get; set; }

    [ForeignKey("KintaiZokuseiId")]
    [InverseProperty("Syains")]
    public virtual KintaiZokusei KintaiZokusei { get; set; } = null!;

    [InverseProperty("Syain")]
    public virtual ICollection<MessageContent> MessageContents { get; set; } = new List<MessageContent>();

    [InverseProperty("Syain")]
    public virtual ICollection<NippouYotei> NippouYoteis { get; set; } = new List<NippouYotei>();

    [InverseProperty("Syain")]
    public virtual ICollection<Nippou> Nippous { get; set; } = new List<Nippou>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<OvertimeAlert> OvertimeAlerts { get; set; } = new List<OvertimeAlert>();

    [InverseProperty("Syain")]
    public virtual ICollection<PcLog> PcLogs { get; set; } = new List<PcLog>();

    [ForeignKey("SyainBaseId")]
    [InverseProperty("Syains")]
    public virtual SyainBasis SyainBase { get; set; } = null!;

    [InverseProperty("Syain")]
    public virtual ICollection<UkagaiHeader> UkagaiHeaders { get; set; } = new List<UkagaiHeader>();

    [InverseProperty("Syain")]
    public virtual ICollection<UnpaidLeaveAlert> UnpaidLeaveAlerts { get; set; } = new List<UnpaidLeaveAlert>();

    [ForeignKey("UserRoleId")]
    [InverseProperty("Syains")]
    public virtual UserRole UserRole { get; set; } = null!;

    [InverseProperty("InputSyain")]
    public virtual ICollection<WorkStatusSummary> WorkStatusSummaryInputSyains { get; set; } = new List<WorkStatusSummary>();

    [InverseProperty("Syain")]
    public virtual ICollection<WorkStatusSummary> WorkStatusSummarySyains { get; set; } = new List<WorkStatusSummary>();

    [InverseProperty("EditSyain")]
    public virtual ICollection<WorkingHour> WorkingHourEditSyains { get; set; } = new List<WorkingHour>();

    [InverseProperty("Syain")]
    public virtual ICollection<WorkingHour> WorkingHourSyains { get; set; } = new List<WorkingHour>();
}