// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 社員BASEマスタ
/// </summary>
[Table("syain_bases")]
public partial class SyainBasis
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// NAME
    /// </summary>
    [Column("name")]
    [StringLength(100)]
    public string? Name { get; set; }

    /// <summary>
    /// CODE
    /// </summary>
    [Column("code")]
    [StringLength(5)]
    public string Code { get; set; } = null!;

    [InverseProperty("SyainBase")]
    public virtual ICollection<AnkenSansyouRireki> AnkenSansyouRirekis { get; set; } = new List<AnkenSansyouRireki>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<Anken> Ankens { get; set; } = new List<Anken>();

    [InverseProperty("Bumoncyo")]
    public virtual ICollection<BusyoBasis> BusyoBases { get; set; } = new List<BusyoBasis>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<KingsJuchuSansyouRireki> KingsJuchuSansyouRirekis { get; set; } = new List<KingsJuchuSansyouRireki>();

    [InverseProperty("EigyoBaseSyain")]
    public virtual ICollection<KokyakuKaisha> KokyakuKaishaEigyoBaseSyains { get; set; } = new List<KokyakuKaisha>();

    [InverseProperty("SyokaiBaseSyain")]
    public virtual ICollection<KokyakuKaisha> KokyakuKaishaSyokaiBaseSyains { get; set; } = new List<KokyakuKaisha>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<KokyakuKaisyaSansyouRireki> KokyakuKaisyaSansyouRirekis { get; set; } = new List<KokyakuKaisyaSansyouRireki>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<KyuukaKanri> KyuukaKanris { get; set; } = new List<KyuukaKanri>();

    [InverseProperty("SendSyainBase")]
    public virtual ICollection<MikakuteiTsuchiRireki> MikakuteiTsuchiRirekis { get; set; } = new List<MikakuteiTsuchiRireki>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<OvertimeExcessLimit> OvertimeExcessLimits { get; set; } = new List<OvertimeExcessLimit>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<SyainPhoto> SyainPhotos { get; set; } = new List<SyainPhoto>();

    [InverseProperty("TsuchiSyainBase")]
    public virtual ICollection<SyainTsuchiRirekiRel> SyainTsuchiRirekiRels { get; set; } = new List<SyainTsuchiRirekiRel>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<Syain> Syains { get; set; } = new List<Syain>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<YukyuKeikaku> YukyuKeikakus { get; set; } = new List<YukyuKeikaku>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<YukyuRireki> YukyuRirekis { get; set; } = new List<YukyuRireki>();

    [InverseProperty("SyainBase")]
    public virtual ICollection<YuukyuuZan> YuukyuuZans { get; set; } = new List<YuukyuuZan>();
}