// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 社員写真
/// </summary>
[Table("syain_photos")]
public partial class SyainPhoto
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 連番
    /// </summary>
    [Column("seq")]
    public int Seq { get; set; }

    /// <summary>
    /// 写真名
    /// </summary>
    [Column("photo_name")]
    [StringLength(96)]
    public string PhotoName { get; set; } = null!;

    /// <summary>
    /// アップロード時間
    /// </summary>
    [Column("upload_time", TypeName = "timestamp(6) without time zone")]
    public DateTime UploadTime { get; set; }

    /// <summary>
    /// SELECTED
    /// </summary>
    [Column("selected")]
    public bool Selected { get; set; }

    /// <summary>
    /// DELETED
    /// </summary>
    [Column("deleted")]
    public bool Deleted { get; set; }

    [InverseProperty("SyainPhoto")]
    public virtual ICollection<PhotoAfterProcessTnData> PhotoAfterProcessTnData { get; set; } = new List<PhotoAfterProcessTnData>();

    [InverseProperty("SyainPhoto")]
    public virtual ICollection<PhotoData> PhotoData { get; set; } = new List<PhotoData>();

    [ForeignKey("SyainBaseId")]
    [InverseProperty("SyainPhotos")]
    public virtual SyainBasis SyainBase { get; set; } = null!;
}