// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 出勤区分
/// </summary>
[Table("syukkin_kubuns")]
public partial class SyukkinKubun
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 出勤区分名称
    /// </summary>
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 出勤区分略名
    /// </summary>
    [Column("name_ryaku")]
    [StringLength(10)]
    public string NameRyaku { get; set; } = null!;

    /// <summary>
    /// 出勤フラグ
    /// </summary>
    [Column("is_syukkin")]
    public bool IsSyukkin { get; set; }

    /// <summary>
    /// 休暇フラグ
    /// </summary>
    [Column("is_vacation")]
    public bool IsVacation { get; set; }

    /// <summary>
    /// 休日フラグ
    /// </summary>
    [Column("is_holiday")]
    public bool IsHoliday { get; set; }

    /// <summary>
    /// 出勤区分1に必要な区分フラグ
    /// </summary>
    [Column("is_need_kubun1")]
    public bool IsNeedKubun1 { get; set; }

    /// <summary>
    /// 出勤区分2に必要な区分フラグ
    /// </summary>
    [Column("is_need_kubun2")]
    public bool IsNeedKubun2 { get; set; }

    [InverseProperty("SyukkinKubunId1Navigation")]
    public virtual ICollection<KyuukaKanri> KyuukaKanriSyukkinKubunId1Navigations { get; set; } = new List<KyuukaKanri>();

    [InverseProperty("SyukkinKubunId2Navigation")]
    public virtual ICollection<KyuukaKanri> KyuukaKanriSyukkinKubunId2Navigations { get; set; } = new List<KyuukaKanri>();

    [InverseProperty("SyukkinKubunId1Navigation")]
    public virtual ICollection<Nippou> NippouSyukkinKubunId1Navigations { get; set; } = new List<Nippou>();

    [InverseProperty("SyukkinKubunId2Navigation")]
    public virtual ICollection<Nippou> NippouSyukkinKubunId2Navigations { get; set; } = new List<Nippou>();
}