// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 伺い入力ヘッダ
/// </summary>
[Table("ukagai_headers")]
public partial class UkagaiHeader
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 申請年月日
    /// </summary>
    [Column("shinsei_ymd")]
    public DateOnly ShinseiYmd { get; set; }

    /// <summary>
    /// 承認社員ID
    /// </summary>
    [Column("shonin_syain_id")]
    public long? ShoninSyainId { get; set; }

    /// <summary>
    /// 承認年月日
    /// </summary>
    [Column("shonin_ymd")]
    public DateOnly? ShoninYmd { get; set; }

    /// <summary>
    /// 最終承認社員ID
    /// </summary>
    [Column("last_shonin_syain_id")]
    public long? LastShoninSyainId { get; set; }

    /// <summary>
    /// 最終承認年月日
    /// </summary>
    [Column("last_shonin_ymd")]
    public DateOnly? LastShoninYmd { get; set; }

    /// <summary>
    /// 作業日付
    /// </summary>
    [Column("work_ymd")]
    public DateOnly WorkYmd { get; set; }

    /// <summary>
    /// 作業開始時刻
    /// </summary>
    [Column("kaishi_jikoku")]
    public TimeOnly? KaishiJikoku { get; set; }

    /// <summary>
    /// 作業終了時刻
    /// </summary>
    [Column("syuryo_jikoku")]
    public TimeOnly? SyuryoJikoku { get; set; }

    /// <summary>
    /// 備考
    /// </summary>
    [Column("biko")]
    [StringLength(4000)]
    public string? Biko { get; set; }

    /// <summary>
    /// 無効フラグ
    /// </summary>
    [Column("invalid")]
    public bool Invalid { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("UkagaiHeaders")]
    public virtual Syain Syain { get; set; } = null!;

    [InverseProperty("UkagaiHeader")]
    public virtual ICollection<UkagaiShinsei> UkagaiShinseis { get; set; } = new List<UkagaiShinsei>();

    [InverseProperty("UkagaiHeader")]
    public virtual ICollection<WorkingHour> WorkingHours { get; set; } = new List<WorkingHour>();
}