// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 伺い申請情報
/// </summary>
[Table("ukagai_shinseis")]
public partial class UkagaiShinsei
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 伺い入力ヘッダID
    /// </summary>
    [Column("ukagai_header_id")]
    public long UkagaiHeaderId { get; set; }

    [ForeignKey("UkagaiHeaderId")]
    [InverseProperty("UkagaiShinseis")]
    public virtual UkagaiHeader UkagaiHeader { get; set; } = null!;
}