// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 有給未取得アラート
/// </summary>
[Table("unpaid_leave_alerts")]
public partial class UnpaidLeaveAlert
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// サービス実行履歴ID
    /// </summary>
    [Column("service_execute_history_id")]
    public long ServiceExecuteHistoryId { get; set; }

    /// <summary>
    /// アラート日時
    /// </summary>
    [Column("datetime", TypeName = "timestamp without time zone")]
    public DateTime Datetime { get; set; }

    /// <summary>
    /// 有給未取得数
    /// </summary>
    [Column("unused_paid_leave_count")]
    public int UnusedPaidLeaveCount { get; set; }

    [ForeignKey("ServiceExecuteHistoryId")]
    [InverseProperty("UnpaidLeaveAlerts")]
    public virtual ServiceExecuteHistory ServiceExecuteHistory { get; set; } = null!;

    [ForeignKey("SyainId")]
    [InverseProperty("UnpaidLeaveAlerts")]
    public virtual Syain Syain { get; set; } = null!;
}