// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// ロール
/// </summary>
[Table("user_roles")]
public partial class UserRole
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// コード
    /// </summary>
    [Column("code")]
    public short Code { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Column("name")]
    [StringLength(20)]
    public string Name { get; set; } = null!;

    /// <summary>
    /// 順序
    /// </summary>
    [Column("jyunjo")]
    public short Jyunjo { get; set; }

    [InverseProperty("UserRole")]
    public virtual ICollection<Syain> Syains { get; set; } = new List<Syain>();
}