// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 勤怠打刻
/// </summary>
[Table("working_hours")]
public partial class WorkingHour
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 日付
    /// </summary>
    [Column("hiduke")]
    public DateOnly Hiduke { get; set; }

    /// <summary>
    /// 出勤緯度
    /// </summary>
    [Column("syukkin_latitude")]
    [Precision(9, 7)]
    public decimal SyukkinLatitude { get; set; }

    /// <summary>
    /// 出勤経度
    /// </summary>
    [Column("syukkin_longitude")]
    [Precision(10, 7)]
    public decimal SyukkinLongitude { get; set; }

    /// <summary>
    /// 退勤緯度
    /// </summary>
    [Column("taikin_latitude")]
    [Precision(9, 7)]
    public decimal TaikinLatitude { get; set; }

    /// <summary>
    /// 退勤経度
    /// </summary>
    [Column("taikin_longitude")]
    [Precision(10, 7)]
    public decimal TaikinLongitude { get; set; }

    /// <summary>
    /// 出勤時間
    /// </summary>
    [Column("syukkin_time", TypeName = "timestamp without time zone")]
    public DateTime? SyukkinTime { get; set; }

    /// <summary>
    /// 退勤時間
    /// </summary>
    [Column("taikin_time", TypeName = "timestamp without time zone")]
    public DateTime? TaikinTime { get; set; }

    /// <summary>
    /// 修正フラグ
    /// </summary>
    [Column("edited")]
    public bool Edited { get; set; }

    /// <summary>
    /// 削除フラグ
    /// </summary>
    [Column("deleted")]
    public bool Deleted { get; set; }

    /// <summary>
    /// 修正社員ID
    /// </summary>
    [Column("edit_syain_id")]
    public long? EditSyainId { get; set; }

    /// <summary>
    /// 伺い入力ヘッダID
    /// </summary>
    [Column("ukagai_header_id")]
    public long? UkagaiHeaderId { get; set; }

    [ForeignKey("EditSyainId")]
    [InverseProperty("WorkingHourEditSyains")]
    public virtual Syain? EditSyain { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("WorkingHourSyains")]
    public virtual Syain Syain { get; set; } = null!;

    [ForeignKey("UkagaiHeaderId")]
    [InverseProperty("WorkingHours")]
    public virtual UkagaiHeader? UkagaiHeader { get; set; }
}