// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 労働状況集計
/// </summary>
[Table("work_status_summaries")]
public partial class WorkStatusSummary
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 報告月
    /// </summary>
    [Column("report_ymd")]
    public DateOnly ReportYmd { get; set; }

    /// <summary>
    /// 社員ID
    /// </summary>
    [Column("syain_id")]
    public long SyainId { get; set; }

    /// <summary>
    /// 日数/時間
    /// </summary>
    [Column("nissu_time")]
    [StringLength(10)]
    public string NissuTime { get; set; } = null!;

    /// <summary>
    /// 回数
    /// </summary>
    [Column("count")]
    public short? Count { get; set; }

    /// <summary>
    /// 状況
    /// </summary>
    [Column("jokyo")]
    [StringLength(2000)]
    public string? Jokyo { get; set; }

    /// <summary>
    /// 対策
    /// </summary>
    [Column("taisaku")]
    [StringLength(2000)]
    public string? Taisaku { get; set; }

    /// <summary>
    /// コメント入力者ID
    /// </summary>
    [Column("input_syain_id")]
    public long? InputSyainId { get; set; }

    [ForeignKey("InputSyainId")]
    [InverseProperty("WorkStatusSummaryInputSyains")]
    public virtual Syain? InputSyain { get; set; }

    [ForeignKey("SyainId")]
    [InverseProperty("WorkStatusSummarySyains")]
    public virtual Syain Syain { get; set; } = null!;
}