// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 計画有給休暇明細
/// </summary>
[Table("yukyu_keikaku_meisais")]
public partial class YukyuKeikakuMeisai
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 計画有給ID
    /// </summary>
    [Column("yukyu_keikaku_id")]
    public long YukyuKeikakuId { get; set; }

    /// <summary>
    /// 計画有給年月日
    /// </summary>
    [Column("ymd")]
    public DateOnly Ymd { get; set; }

    /// <summary>
    /// 特休フラグ
    /// </summary>
    [Column("is_tokukyu")]
    public bool IsTokukyu { get; set; }

    [ForeignKey("YukyuKeikakuId")]
    [InverseProperty("YukyuKeikakuMeisais")]
    public virtual YukyuKeikaku YukyuKeikaku { get; set; } = null!;
}