// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 計画有給休暇
/// </summary>
[Table("yukyu_keikakus")]
public partial class YukyuKeikaku
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 有給年度ID
    /// </summary>
    [Column("yukyu_nendo_id")]
    public long YukyuNendoId { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    [ForeignKey("SyainBaseId")]
    [InverseProperty("YukyuKeikakus")]
    public virtual SyainBasis SyainBase { get; set; } = null!;

    [InverseProperty("YukyuKeikaku")]
    public virtual ICollection<YukyuKeikakuMeisai> YukyuKeikakuMeisais { get; set; } = new List<YukyuKeikakuMeisai>();

    [ForeignKey("YukyuNendoId")]
    [InverseProperty("YukyuKeikakus")]
    public virtual YukyuNendo YukyuNendo { get; set; } = null!;
}