// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 有給履歴
/// </summary>
[Table("yukyu_rirekis")]
public partial class YukyuRireki
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 有給年度ID
    /// </summary>
    [Column("yukyu_nendo_id")]
    public long YukyuNendoId { get; set; }

    /// <summary>
    /// 社員BaseID
    /// </summary>
    [Column("syain_base_id")]
    public long SyainBaseId { get; set; }

    /// <summary>
    /// 有給日数
    /// </summary>
    [Column("wariate")]
    [Precision(4, 2)]
    public decimal Wariate { get; set; }

    /// <summary>
    /// 繰越日数
    /// </summary>
    [Column("kurikoshi")]
    [Precision(4, 2)]
    public decimal Kurikoshi { get; set; }

    /// <summary>
    /// 消化日数
    /// </summary>
    [Column("syouka")]
    [Precision(4, 2)]
    public decimal Syouka { get; set; }

    /// <summary>
    /// 半日有給取得数
    /// </summary>
    [Column("hanniti_kaisuu")]
    public short HannitiKaisuu { get; set; }

    /// <summary>
    /// 計画有給数
    /// </summary>
    [Column("keikaku_yukyu_su")]
    public short KeikakuYukyuSu { get; set; }

    /// <summary>
    /// 計画特休数
    /// </summary>
    [Column("keikaku_tokukyu_su")]
    public short KeikakuTokukyuSu { get; set; }

    [ForeignKey("SyainBaseId")]
    [InverseProperty("YukyuRirekis")]
    public virtual SyainBasis SyainBase { get; set; } = null!;

    [ForeignKey("YukyuNendoId")]
    [InverseProperty("YukyuRirekis")]
    public virtual YukyuNendo YukyuNendo { get; set; } = null!;
}