// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Model;

/// <summary>
/// 有給年度
/// </summary>
[Table("yukyu_nendos")]
public partial class YukyuNendo
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column("id")]
    public long Id { get; set; }

    /// <summary>
    /// 年度
    /// </summary>
    [Column("nendo")]
    public short Nendo { get; set; }

    /// <summary>
    /// 開始日
    /// </summary>
    [Column("start_date")]
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// 終了日
    /// </summary>
    [Column("end_date")]
    public DateOnly EndDate { get; set; }

    /// <summary>
    /// 今年度フラグ
    /// </summary>
    [Column("is_this_year")]
    public bool IsThisYear { get; set; }

    /// <summary>
    /// 更新フラグ
    /// </summary>
    [Column("updated")]
    public bool Updated { get; set; }

    [InverseProperty("YukyuNendo")]
    public virtual ICollection<YukyuKeikaku> YukyuKeikakus { get; set; } = new List<YukyuKeikaku>();

    [InverseProperty("YukyuNendo")]
    public virtual ICollection<YukyuRireki> YukyuRirekis { get; set; } = new List<YukyuRireki>();
}