// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Model.Model;

namespace Model.Data;

public partial class ZouContext : DbContext
{
    public ZouContext(DbContextOptions<ZouContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Anken> Ankens { get; set; }

    public virtual DbSet<AnkenSansyouRireki> AnkenSansyouRirekis { get; set; }

    public virtual DbSet<ApplicationConfig> ApplicationConfigs { get; set; }

    public virtual DbSet<BumonProcess> BumonProcesses { get; set; }

    public virtual DbSet<Busyo> Busyos { get; set; }

    public virtual DbSet<BusyoBasis> BusyoBases { get; set; }

    public virtual DbSet<ContinuousWork> ContinuousWorks { get; set; }

    public virtual DbSet<DairiNyuryokuRireki> DairiNyuryokuRirekis { get; set; }

    public virtual DbSet<FurikyuuZan> FurikyuuZans { get; set; }

    public virtual DbSet<GyoumuType> GyoumuTypes { get; set; }

    public virtual DbSet<Gyousyu> Gyousyus { get; set; }

    public virtual DbSet<Hikadoubi> Hikadoubis { get; set; }

    public virtual DbSet<JissekiKakuteiSimebi> JissekiKakuteiSimebis { get; set; }

    public virtual DbSet<JyutyuSyurui> JyutyuSyuruis { get; set; }

    public virtual DbSet<KaisyaProcess> KaisyaProcesses { get; set; }

    public virtual DbSet<KingsJuchu> KingsJuchus { get; set; }

    public virtual DbSet<KingsJuchuSansyouRireki> KingsJuchuSansyouRirekis { get; set; }

    public virtual DbSet<KintaiZokusei> KintaiZokuseis { get; set; }

    public virtual DbSet<KokyakuKaisha> KokyakuKaishas { get; set; }

    public virtual DbSet<KokyakuKaisyaSansyouRireki> KokyakuKaisyaSansyouRirekis { get; set; }

    public virtual DbSet<KyuukaKanri> KyuukaKanris { get; set; }

    public virtual DbSet<MessageContent> MessageContents { get; set; }

    public virtual DbSet<MikakuteiTsuchiRireki> MikakuteiTsuchiRirekis { get; set; }

    public virtual DbSet<Nippou> Nippous { get; set; }

    public virtual DbSet<NippouAnken> NippouAnkens { get; set; }

    public virtual DbSet<NippouYotei> NippouYoteis { get; set; }

    public virtual DbSet<OvertimeAlert> OvertimeAlerts { get; set; }

    public virtual DbSet<OvertimeExcessLimit> OvertimeExcessLimits { get; set; }

    public virtual DbSet<PcLog> PcLogs { get; set; }

    public virtual DbSet<PhotoAfterProcessTnData> PhotoAfterProcessTnDatas { get; set; }

    public virtual DbSet<PhotoData> PhotoDatas { get; set; }

    public virtual DbSet<ServiceExecute> ServiceExecutes { get; set; }

    public virtual DbSet<ServiceExecuteHistory> ServiceExecuteHistories { get; set; }

    public virtual DbSet<Syain> Syains { get; set; }

    public virtual DbSet<SyainBasis> SyainBases { get; set; }

    public virtual DbSet<SyainPhoto> SyainPhotos { get; set; }

    public virtual DbSet<SyainTsuchiRirekiRel> SyainTsuchiRirekiRels { get; set; }

    public virtual DbSet<SyukkinKubun> SyukkinKubuns { get; set; }

    public virtual DbSet<UkagaiHeader> UkagaiHeaders { get; set; }

    public virtual DbSet<UkagaiShinsei> UkagaiShinseis { get; set; }

    public virtual DbSet<UnpaidLeaveAlert> UnpaidLeaveAlerts { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<WorkStatusSummary> WorkStatusSummaries { get; set; }

    public virtual DbSet<WorkingHour> WorkingHours { get; set; }

    public virtual DbSet<YukyuKeikaku> YukyuKeikakus { get; set; }

    public virtual DbSet<YukyuKeikakuMeisai> YukyuKeikakuMeisais { get; set; }

    public virtual DbSet<YukyuNendo> YukyuNendos { get; set; }

    public virtual DbSet<YukyuRireki> YukyuRirekis { get; set; }

    public virtual DbSet<YuukyuuZan> YuukyuuZans { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("C");

        modelBuilder.Entity<Anken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ankens_pkc");

            entity.ToTable("ankens", tb => tb.HasComment("案件"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.JyutyuSyuruiId).HasComment("受注種類ID");
            entity.Property(e => e.KingsJuchuId).HasComment("KINGS受注ID");
            entity.Property(e => e.KokyakuKaisyaId).HasComment("顧客会社ID");
            entity.Property(e => e.Naiyou).HasComment("案件内容");
            entity.Property(e => e.Name).HasComment("案件名称");
            entity.Property(e => e.SearchName).HasComment("検索用案件名称");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID（責任者）");

            entity.HasOne(d => d.JyutyuSyurui).WithMany(p => p.Ankens).HasConstraintName("ankens_fk2");

            entity.HasOne(d => d.KingsJuchu).WithMany(p => p.Ankens).HasConstraintName("ankens_fk4");

            entity.HasOne(d => d.KokyakuKaisya).WithMany(p => p.Ankens).HasConstraintName("ankens_fk3");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.Ankens).HasConstraintName("ankens_fk1");
        });

        modelBuilder.Entity<AnkenSansyouRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("anken_sansyou_rirekis_pkc");

            entity.ToTable("anken_sansyou_rirekis", tb => tb.HasComment("案件参照履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AnkenId).HasComment("案件ID");
            entity.Property(e => e.SansyouTime).HasComment("参照時間");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");

            entity.HasOne(d => d.Anken).WithMany(p => p.AnkenSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("anken_sansyou_rirekis_fk2");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.AnkenSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("anken_sansyou_rirekis_fk1");
        });

        modelBuilder.Entity<ApplicationConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("application_configs_pkc");

            entity.ToTable("application_configs", tb => tb.HasComment("アプリConfig"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.MsClientId).HasComment("MSクライアントID");
            entity.Property(e => e.MsClientSecret).HasComment("MSクライアントシークレット");
            entity.Property(e => e.MsTenantId).HasComment("MSテナントID");
            entity.Property(e => e.NippoStopDate).HasComment("日報停止日");
            entity.Property(e => e.SmtpPassword).HasComment("SMTPパスワード");
            entity.Property(e => e.SmtpUser).HasComment("SMTPユーザ");
        });

        modelBuilder.Entity<BumonProcess>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("bumon_process_pkc");

            entity.ToTable("bumon_process", tb => tb.HasComment("部門プロセス"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.BusyoBaseId).HasComment("部署BaseID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("コード");
            entity.Property(e => e.Deleted).HasComment("削除フラグ");
            entity.Property(e => e.KaisyaProcessId).HasComment("会社プロセスID");
            entity.Property(e => e.Name).HasComment("名称");
            entity.Property(e => e.OyaId).HasComment("親ID");

            entity.HasOne(d => d.BusyoBase).WithMany(p => p.BumonProcesses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bumon_process_fk2");

            entity.HasOne(d => d.KaisyaProcess).WithMany(p => p.BumonProcesses).HasConstraintName("bumon_process_fk3");

            entity.HasOne(d => d.Oya).WithMany(p => p.InverseOya).HasConstraintName("bumon_process_fk1");
        });

        modelBuilder.Entity<Busyo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("busyos_pkc");

            entity.ToTable("busyos", tb => tb.HasComment("部署マスタ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.BusyoBaseId).HasComment("部署BaseID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("部署番号");
            entity.Property(e => e.EndYmd).HasComment("有効終了日");
            entity.Property(e => e.IsActive).HasComment("アクティブフラグ");
            entity.Property(e => e.Jyunjyo).HasComment("並び順序");
            entity.Property(e => e.KaikeiCode)
                .IsFixedLength()
                .HasComment("会計コード（日報システム上での部署コード）");
            entity.Property(e => e.KanaName).HasComment("部署カナ名称");
            entity.Property(e => e.KasyoCode)
                .IsFixedLength()
                .HasComment("箇所コード（精算システム上の処理単位）");
            entity.Property(e => e.KeiriCode)
                .IsFixedLength()
                .HasComment("経理コード（仕訳生成時の会計単位）");
            entity.Property(e => e.Name).HasComment("部署名称");
            entity.Property(e => e.OyaCode)
                .IsFixedLength()
                .HasComment("親部署番号");
            entity.Property(e => e.OyaId).HasComment("親ID");
            entity.Property(e => e.Ryakusyou).HasComment("略称");
            entity.Property(e => e.ShoninBusyoId).HasComment("承認部署ID");
            entity.Property(e => e.StartYmd).HasComment("有効開始日");

            entity.HasOne(d => d.BusyoBase).WithMany(p => p.Busyos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("busyos_fk3");

            entity.HasOne(d => d.Oya).WithMany(p => p.InverseOya).HasConstraintName("busyos_fk2");

            entity.HasOne(d => d.ShoninBusyo).WithMany(p => p.InverseShoninBusyo).HasConstraintName("busyos_fk1");
        });

        modelBuilder.Entity<BusyoBasis>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("busyo_bases_pkc");

            entity.ToTable("busyo_bases", tb => tb.HasComment("部署BASEマスタ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.BumoncyoId).HasComment("部門長_ID");
            entity.Property(e => e.Name).HasComment("名前");

            entity.HasOne(d => d.Bumoncyo).WithMany(p => p.BusyoBases).HasConstraintName("busyo_bases_fk1");
        });

        modelBuilder.Entity<ContinuousWork>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("continuous_works_PKC");

            entity.ToTable("continuous_works", tb => tb.HasComment("連続勤務"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Date).HasComment("日時");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.WorkingDay).HasComment("連続勤務日数");

            entity.HasOne(d => d.Syain).WithMany(p => p.ContinuousWorks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("continuous_works_fk2");
        });

        modelBuilder.Entity<DairiNyuryokuRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("dairi_nyuryoku_rirekies_pkc");

            entity.ToTable("dairi_nyuryoku_rirekis", tb => tb.HasComment("代理入力履歴"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("nextval('dairi_nyuryoku_rirekies_id_seq'::regclass)")
                .HasComment("ID");
            entity.Property(e => e.DairiNyuryokuSyainId).HasComment("代理入力社員ID");
            entity.Property(e => e.DairiNyuryokuTime).HasComment("代理入力日時");
            entity.Property(e => e.Invalid).HasComment("無効フラグ");
            entity.Property(e => e.NippouId).HasComment("日報実績ID");

            entity.HasOne(d => d.DairiNyuryokuSyain).WithMany(p => p.DairiNyuryokuRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("dairi_nyuryoku_rirekies_fk2");

            entity.HasOne(d => d.Nippou).WithMany(p => p.DairiNyuryokuRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("dairi_nyuryoku_rirekies_fk1");
        });

        modelBuilder.Entity<FurikyuuZan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("furikyuu_zans_pkc");

            entity.ToTable("furikyuu_zans", tb => tb.HasComment("振替休暇残"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.DaikyuuKigenYmd).HasComment("代休期限年月日");
            entity.Property(e => e.IsOneDay).HasComment("1日フラグ");
            entity.Property(e => e.KyuujitsuSyukkinYmd).HasComment("休日出勤年月日");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.SyutokuYmd1).HasComment("取得年月日1");
            entity.Property(e => e.SyutokuYmd2).HasComment("取得年月日2");
            entity.Property(e => e.SyutokuYoteiYmd).HasComment("振休取得予定日");

            entity.HasOne(d => d.Syain).WithMany(p => p.FurikyuuZans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("furikyuu_zans_fk1");
        });

        modelBuilder.Entity<GyoumuType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("gyoumu_types_pkc");

            entity.ToTable("gyoumu_types", tb => tb.HasComment("業務タイプ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Deleted).HasComment("削除フラグ");
            entity.Property(e => e.Jyunjyo).HasComment("表示順序");
            entity.Property(e => e.Name).HasComment("業務種別名称");
        });

        modelBuilder.Entity<Gyousyu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("gyousyus_pkc");

            entity.ToTable("gyousyus", tb => tb.HasComment("業種マスタ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("業種コード");
            entity.Property(e => e.Name).HasComment("業種名称");
        });

        modelBuilder.Entity<Hikadoubi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("hikadoubis_pkc");

            entity.ToTable("hikadoubis", tb => tb.HasComment("非稼働日"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Ymd).HasComment("年月日");
        });

        modelBuilder.Entity<JissekiKakuteiSimebi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("jisseki_kakutei_simebis_pkc");

            entity.ToTable("jisseki_kakutei_simebis", tb => tb.HasComment("実績確定締め日"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.KakuteiKigenYmd).HasComment("確定期限");
        });

        modelBuilder.Entity<JyutyuSyurui>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("jyutyu_syuruis_pkc");

            entity.ToTable("jyutyu_syuruis", tb => tb.HasComment("受注種類"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("受注種類コード");
            entity.Property(e => e.Name).HasComment("受注種類名称");
        });

        modelBuilder.Entity<KaisyaProcess>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kaisya_process_pkc");

            entity.ToTable("kaisya_process", tb => tb.HasComment("会社プロセス"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("コード");
            entity.Property(e => e.Deleted).HasComment("削除フラグ");
            entity.Property(e => e.Name).HasComment("名称");
            entity.Property(e => e.OyaId).HasComment("親ID");

            entity.HasOne(d => d.Oya).WithMany(p => p.InverseOya).HasConstraintName("kaisya_process_fk1");
        });

        modelBuilder.Entity<KingsJuchu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kings_juchus_pkc");

            entity.ToTable("kings_juchus", tb => tb.HasComment("KINGS受注登録"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Biko).HasComment("備考");
            entity.Property(e => e.Bukken).HasComment("件名");
            entity.Property(e => e.BusyoId).HasComment("部署ID（施工部門）");
            entity.Property(e => e.ChaYmd).HasComment("着工日");
            entity.Property(e => e.EntYmd).HasComment("受注登録日");
            entity.Property(e => e.HiyouShubetuCd).HasComment("費用種別コード");
            entity.Property(e => e.HiyouShubetuCdName).HasComment("費用種別名");
            entity.Property(e => e.IriBusCd)
                .IsFixedLength()
                .HasComment("送り元部署コード");
            entity.Property(e => e.IsGenkaToketu).HasComment("原価凍結フラグ");
            entity.Property(e => e.JsriCd)
                .IsFixedLength()
                .HasComment("受注種類コード");
            entity.Property(e => e.JucCd)
                .IsFixedLength()
                .HasComment("受注会社コード");
            entity.Property(e => e.JucKin).HasComment("受注金額");
            entity.Property(e => e.JucKn).HasComment("受注先カナ");
            entity.Property(e => e.JucNm).HasComment("受注先");
            entity.Property(e => e.JucYmd).HasComment("受注日");
            entity.Property(e => e.JuchuuGyoNo).HasComment("受注行番号");
            entity.Property(e => e.JuchuuNo).HasComment("受注番号");
            entity.Property(e => e.KeiKn).HasComment("契約先カナ");
            entity.Property(e => e.KeiNm).HasComment("契約先");
            entity.Property(e => e.KeiyakuJoutaiKbnName).HasComment("契約状態区分名");
            entity.Property(e => e.KnyYmd).HasComment("入金計画日");
            entity.Property(e => e.KurYmd).HasComment("売上計画日");
            entity.Property(e => e.Nendo).HasComment("年度");
            entity.Property(e => e.NsyYmd).HasComment("納期施工");
            entity.Property(e => e.OkrTanCd1)
                .IsFixedLength()
                .HasComment("送り担当者コード");
            entity.Property(e => e.OkrTanNm1).HasComment("送り担当者氏名");
            entity.Property(e => e.ProjectNo).HasComment("プロジェクト番号");
            entity.Property(e => e.SearchBukken).HasComment("検索用件名");
            entity.Property(e => e.SearchJucKn).HasComment("検索用受注先カナ");
            entity.Property(e => e.SearchJucNm).HasComment("検索用受注先");
            entity.Property(e => e.SearchKeiKn).HasComment("検索用契約先カナ");
            entity.Property(e => e.SearchKeiNm).HasComment("検索用契約先");
            entity.Property(e => e.SekouBumonCd)
                .IsFixedLength()
                .HasComment("施工部門コード");
            entity.Property(e => e.ShouhinName).HasComment("商品名");
            entity.Property(e => e.ToketuYmd).HasComment("原価凍結日");
            entity.Property(e => e.UkeTanCd1)
                .IsFixedLength()
                .HasComment("受け担当者コード");
            entity.Property(e => e.UkeTanNm1).HasComment("受け担当者氏名");

            entity.HasOne(d => d.Busyo).WithMany(p => p.KingsJuchus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kings_juchus_fk1");
        });

        modelBuilder.Entity<KingsJuchuSansyouRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kings_juchu_sansyou_rirekis_pkc");

            entity.ToTable("kings_juchu_sansyou_rirekis", tb => tb.HasComment("KINGS受注参照履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.KingsJuchuId).HasComment("KINGS受注ID");
            entity.Property(e => e.SansyouTime).HasComment("参照時間");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");

            entity.HasOne(d => d.KingsJuchu).WithMany(p => p.KingsJuchuSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kings_juchu_sansyou_rirekis_fk2");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.KingsJuchuSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kings_juchu_sansyou_rirekis_fk1");
        });

        modelBuilder.Entity<KintaiZokusei>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kintai_zokuseis_pkc");

            entity.ToTable("kintai_zokuseis", tb => tb.HasComment("勤怠属性"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.IsMinashi).HasComment("みなしフラグ");
            entity.Property(e => e.IsOvertimeLimit3m).HasComment("残業制限時間累計期間3ヶ月フラグ");
            entity.Property(e => e.MaxLimitTime).HasComment("最大限界時間:0は無制限");
            entity.Property(e => e.Name).HasComment("名称");
            entity.Property(e => e.SeigenTime).HasComment("制限時間:0は無制限");
        });

        modelBuilder.Entity<KokyakuKaisha>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kokyaku_kaishas_pkc");

            entity.ToTable("kokyaku_kaishas", tb => tb.HasComment("顧客会社"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code).HasComment("顧客コード");
            entity.Property(e => e.EigyoBaseSyainId).HasComment("社員BaseID（営業担当）");
            entity.Property(e => e.Fax).HasComment("FAX番号");
            entity.Property(e => e.GyousyuCode)
                .IsFixedLength()
                .HasComment("業種コード");
            entity.Property(e => e.GyousyuId).HasComment("業種ID");
            entity.Property(e => e.Jyuusyo1).HasComment("住所１");
            entity.Property(e => e.Jyuusyo2).HasComment("住所２");
            entity.Property(e => e.Memo).HasComment("メモ");
            entity.Property(e => e.Name).HasComment("顧客名称");
            entity.Property(e => e.NameKana).HasComment("顧客名カナ");
            entity.Property(e => e.Ryakusyou).HasComment("顧客名略称");
            entity.Property(e => e.SearchName).HasComment("検索用顧客名称");
            entity.Property(e => e.SearchNameKana).HasComment("検索用顧客名称カナ");
            entity.Property(e => e.Shiten).HasComment("支店名称");
            entity.Property(e => e.SyokaiBaseSyainId).HasComment("社員BaseID（紹介担当）");
            entity.Property(e => e.SyoukaiNaiyou).HasComment("紹介内容");
            entity.Property(e => e.SyoukaisyaCode).HasComment("紹介者コード");
            entity.Property(e => e.Tel).HasComment("TEL番号");
            entity.Property(e => e.Url).HasComment("URL");
            entity.Property(e => e.YuubinBangou).HasComment("郵便番号");

            entity.HasOne(d => d.EigyoBaseSyain).WithMany(p => p.KokyakuKaishaEigyoBaseSyains).HasConstraintName("kokyaku_kaishas_fk2");

            entity.HasOne(d => d.Gyousyu).WithMany(p => p.KokyakuKaishas).HasConstraintName("kokyaku_kaishas_fk3");

            entity.HasOne(d => d.SyokaiBaseSyain).WithMany(p => p.KokyakuKaishaSyokaiBaseSyains).HasConstraintName("kokyaku_kaishas_fk1");
        });

        modelBuilder.Entity<KokyakuKaisyaSansyouRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kokyaku_kaisya_sansyou_rirekis_pkc");

            entity.ToTable("kokyaku_kaisya_sansyou_rirekis", tb => tb.HasComment("顧客会社参照履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.KokyakuKaisyaId).HasComment("顧客会社_ID");
            entity.Property(e => e.SansyouTime).HasComment("参照時間");
            entity.Property(e => e.SyainBaseId).HasComment("社員BASE_ID");

            entity.HasOne(d => d.KokyakuKaisya).WithMany(p => p.KokyakuKaisyaSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kokyaku_kaisya_sansyou_rirekis_fk2");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.KokyakuKaisyaSansyouRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kokyaku_kaisya_sansyou_rirekis_fk1");
        });

        modelBuilder.Entity<KyuukaKanri>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("kyuuka_kanris_pkc");

            entity.ToTable("kyuuka_kanris", tb => tb.HasComment("休暇管理"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.HotenRudouJikan).HasComment("補填労働時間");
            entity.Property(e => e.KyuukaKubun)
                .IsFixedLength()
                .HasComment("休暇区分");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.SyoukaFurikyuuZanId).HasComment("振替休暇残ID");
            entity.Property(e => e.SyukkinKubunId1).HasComment("出勤区分ID1");
            entity.Property(e => e.SyukkinKubunId2).HasComment("出勤区分ID2");
            entity.Property(e => e.TaisyouYmd).HasComment("対象年月日");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.KyuukaKanris)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("kyuuka_kanris_fk3");

            entity.HasOne(d => d.SyoukaFurikyuuZan).WithMany(p => p.KyuukaKanris).HasConstraintName("kyuuka_kanris_fk4");

            entity.HasOne(d => d.SyukkinKubunId1Navigation).WithMany(p => p.KyuukaKanriSyukkinKubunId1Navigations).HasConstraintName("kyuuka_kanris_fk2");

            entity.HasOne(d => d.SyukkinKubunId2Navigation).WithMany(p => p.KyuukaKanriSyukkinKubunId2Navigations).HasConstraintName("kyuuka_kanris_fk1");
        });

        modelBuilder.Entity<MessageContent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("message_contents_pkc");

            entity.ToTable("message_contents", tb => tb.HasComment("送信内容"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Content).HasComment("内容");
            entity.Property(e => e.SendDatetime).HasComment("送信時刻");
            entity.Property(e => e.SyainId).HasComment("社員ID");

            entity.HasOne(d => d.Syain).WithMany(p => p.MessageContents)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("message_contents_fk5");
        });

        modelBuilder.Entity<MikakuteiTsuchiRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("mikakutei_tsuchi_rirekis_pkc");

            entity.ToTable("mikakutei_tsuchi_rirekis", tb => tb.HasComment("未確定通知送信履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.JissekiKakuteiSimebiId).HasComment("実績確定締め日ID");
            entity.Property(e => e.SendMessage).HasComment("送信メッセージ");
            entity.Property(e => e.SendSyainBaseId).HasComment("通知送信社員ID");
            entity.Property(e => e.TuutiSousinNitizi).HasComment("通知送信日時");

            entity.HasOne(d => d.JissekiKakuteiSimebi).WithMany(p => p.MikakuteiTsuchiRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mikakutei_tsuchi_rirekis_fk1");

            entity.HasOne(d => d.SendSyainBase).WithMany(p => p.MikakuteiTsuchiRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mikakutei_tsuchi_rirekis_fk2");
        });

        modelBuilder.Entity<Nippou>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("nippous_pkc");

            entity.ToTable("nippous", tb => tb.HasComment("日報実績"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.DJitsudou).HasComment("土祝祭日実働");
            entity.Property(e => e.DShinyaZangyo).HasComment("土祝祭日深夜残業");
            entity.Property(e => e.DWarimashi).HasComment("土祝祭日割増");
            entity.Property(e => e.DZangyo).HasComment("土祝祭日残業");
            entity.Property(e => e.HJitsudou).HasComment("平日実働");
            entity.Property(e => e.HShinyaZangyo).HasComment("平日深夜残業");
            entity.Property(e => e.HWarimashi).HasComment("平日割増");
            entity.Property(e => e.HZangyo).HasComment("平日残業");
            entity.Property(e => e.IsRendouZumi).HasComment("連動済フラグ");
            entity.Property(e => e.KakuteiYmd).HasComment("確定年月日");
            entity.Property(e => e.NJitsudou).HasComment("法定休日実働");
            entity.Property(e => e.NShinya).HasComment("法定休日深夜");
            entity.Property(e => e.NippouYmd).HasComment("実績年月日");
            entity.Property(e => e.RendouYmd).HasComment("連動年月日");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.SyukkinHm1).HasComment("出勤時間1");
            entity.Property(e => e.SyukkinHm2).HasComment("出勤時間2");
            entity.Property(e => e.SyukkinHm3).HasComment("出勤時間3");
            entity.Property(e => e.SyukkinKubunId1).HasComment("出勤区分ID1");
            entity.Property(e => e.SyukkinKubunId2).HasComment("出勤区分ID2");
            entity.Property(e => e.TaisyutsuHm1).HasComment("退出時間1");
            entity.Property(e => e.TaisyutsuHm2).HasComment("退出時間2");
            entity.Property(e => e.TaisyutsuHm3).HasComment("退出時間3");
            entity.Property(e => e.TotalZangyo).HasComment("みなし対象外用残業");
            entity.Property(e => e.Youbi).HasComment("曜日");

            entity.HasOne(d => d.Syain).WithMany(p => p.Nippous)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippous_fk3");

            entity.HasOne(d => d.SyukkinKubunId1Navigation).WithMany(p => p.NippouSyukkinKubunId1Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippous_fk2");

            entity.HasOne(d => d.SyukkinKubunId2Navigation).WithMany(p => p.NippouSyukkinKubunId2Navigations).HasConstraintName("nippous_fk1");
        });

        modelBuilder.Entity<NippouAnken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("nippou_ankens_pkc");

            entity.ToTable("nippou_ankens", tb => tb.HasComment("日報実績⇔案件"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AnkenName).HasComment("案件名");
            entity.Property(e => e.AnkensId).HasComment("案件_ID");
            entity.Property(e => e.BumonProcessId).HasComment("部門プロセスID");
            entity.Property(e => e.IsLinked).HasComment("原価連携フラグ");
            entity.Property(e => e.JissekiJikan).HasComment("実績時間");
            entity.Property(e => e.KokyakuKaisyaId).HasComment("顧客会社ID");
            entity.Property(e => e.KokyakuName).HasComment("顧客名");
            entity.Property(e => e.NippouId).HasComment("日報実績ID");

            entity.HasOne(d => d.Ankens).WithMany(p => p.NippouAnkens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippou_ankens_fk3");

            entity.HasOne(d => d.BumonProcess).WithMany(p => p.NippouAnkens).HasConstraintName("nippou_ankens_fk1");

            entity.HasOne(d => d.KokyakuKaisya).WithMany(p => p.NippouAnkens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippou_ankens_fk2");

            entity.HasOne(d => d.Nippou).WithMany(p => p.NippouAnkens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippou_ankens_fk4");
        });

        modelBuilder.Entity<NippouYotei>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("nippou_yoteis_pkc");

            entity.ToTable("nippou_yoteis", tb => tb.HasComment("日報予定"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.NippouYoteiYmd).HasComment("予定年月日");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.Worked).HasComment("出勤フラグ");
            entity.Property(e => e.ZangyouJikan).HasComment("残業時間");

            entity.HasOne(d => d.Syain).WithMany(p => p.NippouYoteis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("nippou_yoteis_fk1");
        });

        modelBuilder.Entity<OvertimeAlert>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("overtime_alerts_pkc");

            entity.ToTable("overtime_alerts", tb => tb.HasComment("残業時間アラート:旧warn_overtime_work"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.ServiceExecuteHistoryId).HasComment("サービス実行履歴ID");
            entity.Property(e => e.SyainBaseId).HasComment("社員ID");
            entity.Property(e => e.YearMonth).HasComment("年月");

            entity.HasOne(d => d.ServiceExecuteHistory).WithMany(p => p.OvertimeAlerts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("overtime_alerts_fk1");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.OvertimeAlerts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("overtime_alerts_fk2");
        });

        modelBuilder.Entity<OvertimeExcessLimit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("overtime_excess_limits_pkc");

            entity.ToTable("overtime_excess_limits", tb => tb.HasComment("残業超過制限"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.DisabledYm).HasComment("無効年月");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.OvertimeExcessLimits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("overtime_excess_limits_fk1");
        });

        modelBuilder.Entity<PcLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pc_logs_pkc");

            entity.ToTable("pc_logs", tb => tb.HasComment("PCログ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Datetime).HasComment("日時");
            entity.Property(e => e.PcName).HasComment("コンピューター名");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.UserName).HasComment("ログオンユーザ名");

            entity.HasOne(d => d.Syain).WithMany(p => p.PcLogs).HasConstraintName("pc_logs_fk1");
        });

        modelBuilder.Entity<PhotoAfterProcessTnData>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("photo_after_process_tn_datas_pkc");

            entity.ToTable("photo_after_process_tn_datas", tb => tb.HasComment("社員の顔写真データ（加工後のサムネイル）"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Photo).HasComment("写真");
            entity.Property(e => e.SyainPhotoId).HasComment("社員写真ID");

            entity.HasOne(d => d.SyainPhoto).WithMany(p => p.PhotoAfterProcessTnData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("photo_after_process_tn_datas_fk1");
        });

        modelBuilder.Entity<PhotoData>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("photo_datas_pkc");

            entity.ToTable("photo_datas", tb => tb.HasComment("社員の顔写真データ（加工前）"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Photo).HasComment("写真");
            entity.Property(e => e.SyainPhotoId).HasComment("社員写真ID");

            entity.HasOne(d => d.SyainPhoto).WithMany(p => p.PhotoData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("photo_datas_fk1");
        });

        modelBuilder.Entity<ServiceExecute>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_executes_pkc");

            entity.ToTable("service_executes", tb => tb.HasComment("サービス実行"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Used).HasComment("稼働中?");
        });

        modelBuilder.Entity<ServiceExecuteHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_execute_histories_pkc");

            entity.ToTable("service_execute_histories", tb => tb.HasComment("サービス実行履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.CompletedDatetime).HasComment("完了日時");
            entity.Property(e => e.Content).HasComment("内容");
            entity.Property(e => e.ExecuteDatetime).HasComment("実行開始日時");
        });

        modelBuilder.Entity<Syain>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("syains_pkc");

            entity.ToTable("syains", tb => tb.HasComment("社員マスタ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.BusyoCode)
                .IsFixedLength()
                .HasComment("部署コード");
            entity.Property(e => e.BusyoId).HasComment("部署ID");
            entity.Property(e => e.Code)
                .IsFixedLength()
                .HasComment("社員番号");
            entity.Property(e => e.EMail).HasComment("Ｅ－Ｍａｉｌアドレス");
            entity.Property(e => e.EndYmd).HasComment("有効終了日");
            entity.Property(e => e.GyoumuTypeId).HasComment("業務タイプID");
            entity.Property(e => e.IsGenkaRendou).HasComment("原価連動フラグ");
            entity.Property(e => e.Jyunjyo).HasComment("並び順序");
            entity.Property(e => e.KaisyaCode).HasComment("会社コード");
            entity.Property(e => e.KanaName).HasComment("社員氏名カナ");
            entity.Property(e => e.KeitaiMail).HasComment("携帯Ｍａｉｌアドレス");
            entity.Property(e => e.KingsSyozoku)
                .IsFixedLength()
                .HasComment("KINGS所属");
            entity.Property(e => e.KintaiZokuseiId).HasComment("勤怠属性ID");
            entity.Property(e => e.Kyusyoku).HasComment("級職");
            entity.Property(e => e.Name).HasComment("社員氏名");
            entity.Property(e => e.NyuusyaYmd).HasComment("入社年月日");
            entity.Property(e => e.PhoneNumber).HasComment("電話番号");
            entity.Property(e => e.Retired).HasComment("退職フラグ");
            entity.Property(e => e.Seibetsu).HasComment("性別");
            entity.Property(e => e.StartYmd).HasComment("有効開始日");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.SyokusyuBunruiCode).HasComment("職種分類コード");
            entity.Property(e => e.SyokusyuCode).HasComment("職種コード");
            entity.Property(e => e.UserRoleId).HasComment("ユーザーロールID");

            entity.HasOne(d => d.Busyo).WithMany(p => p.Syains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syains_fk4");

            entity.HasOne(d => d.GyoumuType).WithMany(p => p.Syains).HasConstraintName("syains_fk3");

            entity.HasOne(d => d.KintaiZokusei).WithMany(p => p.Syains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syains_fk2");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.Syains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syains_fk5");

            entity.HasOne(d => d.UserRole).WithMany(p => p.Syains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syains_fk1");
        });

        modelBuilder.Entity<SyainBasis>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("syain_bases_pkc");

            entity.ToTable("syain_bases", tb => tb.HasComment("社員BASEマスタ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code).HasComment("CODE");
            entity.Property(e => e.Name).HasComment("NAME");
        });

        modelBuilder.Entity<SyainPhoto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("syain_photos_pkc");

            entity.ToTable("syain_photos", tb => tb.HasComment("社員写真"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Deleted).HasComment("DELETED");
            entity.Property(e => e.PhotoName).HasComment("写真名");
            entity.Property(e => e.Selected).HasComment("SELECTED");
            entity.Property(e => e.Seq).HasComment("連番");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.UploadTime).HasComment("アップロード時間");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.SyainPhotos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syain_photos_fk1");
        });

        modelBuilder.Entity<SyainTsuchiRirekiRel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("syain_tsuchi_rireki_rels_pkc");

            entity.ToTable("syain_tsuchi_rireki_rels", tb => tb.HasComment("社員⇔未確定通知送信履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.MikakuteiTsuchiRirekiId).HasComment("未確定通知送信履歴ID");
            entity.Property(e => e.TsuchiSyainBaseId).HasComment("通知対象社員ID");

            entity.HasOne(d => d.MikakuteiTsuchiRireki).WithMany(p => p.SyainTsuchiRirekiRels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syain_tsuchi_rireki_rels_fk1");

            entity.HasOne(d => d.TsuchiSyainBase).WithMany(p => p.SyainTsuchiRirekiRels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("syain_tsuchi_rireki_rels_fk2");
        });

        modelBuilder.Entity<SyukkinKubun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("syukkin_kubuns_pkc");

            entity.ToTable("syukkin_kubuns", tb => tb.HasComment("出勤区分"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.IsHoliday).HasComment("休日フラグ");
            entity.Property(e => e.IsNeedKubun1).HasComment("出勤区分1に必要な区分フラグ");
            entity.Property(e => e.IsNeedKubun2).HasComment("出勤区分2に必要な区分フラグ");
            entity.Property(e => e.IsSyukkin).HasComment("出勤フラグ");
            entity.Property(e => e.IsVacation).HasComment("休暇フラグ");
            entity.Property(e => e.Name).HasComment("出勤区分名称");
            entity.Property(e => e.NameRyaku).HasComment("出勤区分略名");
        });

        modelBuilder.Entity<UkagaiHeader>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ukagai_headers_pkc");

            entity.ToTable("ukagai_headers", tb => tb.HasComment("伺い入力ヘッダ"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Biko).HasComment("備考");
            entity.Property(e => e.Invalid).HasComment("無効フラグ");
            entity.Property(e => e.KaishiJikoku).HasComment("作業開始時刻");
            entity.Property(e => e.LastShoninSyainId).HasComment("最終承認社員ID");
            entity.Property(e => e.LastShoninYmd).HasComment("最終承認年月日");
            entity.Property(e => e.ShinseiYmd).HasComment("申請年月日");
            entity.Property(e => e.ShoninSyainId).HasComment("承認社員ID");
            entity.Property(e => e.ShoninYmd).HasComment("承認年月日");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.SyuryoJikoku).HasComment("作業終了時刻");
            entity.Property(e => e.WorkYmd).HasComment("作業日付");

            entity.HasOne(d => d.Syain).WithMany(p => p.UkagaiHeaders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ukagai_headers_fk1");
        });

        modelBuilder.Entity<UkagaiShinsei>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ukagai_shinseis_pkc");

            entity.ToTable("ukagai_shinseis", tb => tb.HasComment("伺い申請情報"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.UkagaiHeaderId).HasComment("伺い入力ヘッダID");

            entity.HasOne(d => d.UkagaiHeader).WithMany(p => p.UkagaiShinseis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ukagai_shinseis_fk1");
        });

        modelBuilder.Entity<UnpaidLeaveAlert>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("unpaid_leave_alerts_pkc");

            entity.ToTable("unpaid_leave_alerts", tb => tb.HasComment("有給未取得アラート"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Datetime).HasComment("アラート日時");
            entity.Property(e => e.ServiceExecuteHistoryId).HasComment("サービス実行履歴ID");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.UnusedPaidLeaveCount).HasComment("有給未取得数");

            entity.HasOne(d => d.ServiceExecuteHistory).WithMany(p => p.UnpaidLeaveAlerts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("unpaid_leave_alerts_fk1");

            entity.HasOne(d => d.Syain).WithMany(p => p.UnpaidLeaveAlerts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("unpaid_leave_alerts_fk2");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_roles_pkc");

            entity.ToTable("user_roles", tb => tb.HasComment("ロール"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Code).HasComment("コード");
            entity.Property(e => e.Jyunjo).HasComment("順序");
            entity.Property(e => e.Name).HasComment("名称");
        });

        modelBuilder.Entity<WorkStatusSummary>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("work_status_summaries_pkc");

            entity.ToTable("work_status_summaries", tb => tb.HasComment("労働状況集計"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Count).HasComment("回数");
            entity.Property(e => e.InputSyainId).HasComment("コメント入力者ID");
            entity.Property(e => e.Jokyo).HasComment("状況");
            entity.Property(e => e.NissuTime).HasComment("日数/時間");
            entity.Property(e => e.ReportYmd).HasComment("報告月");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.Taisaku).HasComment("対策");

            entity.HasOne(d => d.InputSyain).WithMany(p => p.WorkStatusSummaryInputSyains).HasConstraintName("work_status_summaries_fk1");

            entity.HasOne(d => d.Syain).WithMany(p => p.WorkStatusSummarySyains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("work_status_summaries_fk2");
        });

        modelBuilder.Entity<WorkingHour>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("working_hours_pkc");

            entity.ToTable("working_hours", tb => tb.HasComment("勤怠打刻"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.Deleted).HasComment("削除フラグ");
            entity.Property(e => e.EditSyainId).HasComment("修正社員ID");
            entity.Property(e => e.Edited).HasComment("修正フラグ");
            entity.Property(e => e.Hiduke).HasComment("日付");
            entity.Property(e => e.SyainId).HasComment("社員ID");
            entity.Property(e => e.SyukkinLatitude).HasComment("出勤緯度");
            entity.Property(e => e.SyukkinLongitude).HasComment("出勤経度");
            entity.Property(e => e.SyukkinTime).HasComment("出勤時間");
            entity.Property(e => e.TaikinLatitude).HasComment("退勤緯度");
            entity.Property(e => e.TaikinLongitude).HasComment("退勤経度");
            entity.Property(e => e.TaikinTime).HasComment("退勤時間");
            entity.Property(e => e.UkagaiHeaderId).HasComment("伺い入力ヘッダID");

            entity.HasOne(d => d.EditSyain).WithMany(p => p.WorkingHourEditSyains).HasConstraintName("working_hours_fk2");

            entity.HasOne(d => d.Syain).WithMany(p => p.WorkingHourSyains)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("working_hours_fk3");

            entity.HasOne(d => d.UkagaiHeader).WithMany(p => p.WorkingHours).HasConstraintName("working_hours_fk1");
        });

        modelBuilder.Entity<YukyuKeikaku>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("yukyu_keikakus_pkc");

            entity.ToTable("yukyu_keikakus", tb => tb.HasComment("計画有給休暇"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.YukyuNendoId).HasComment("有給年度ID");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.YukyuKeikakus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yukyu_keikakus_fk2");

            entity.HasOne(d => d.YukyuNendo).WithMany(p => p.YukyuKeikakus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yukyu_keikakus_fk1");
        });

        modelBuilder.Entity<YukyuKeikakuMeisai>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("yukyu_keikaku_meisais_pkc");

            entity.ToTable("yukyu_keikaku_meisais", tb => tb.HasComment("計画有給休暇明細"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.IsTokukyu).HasComment("特休フラグ");
            entity.Property(e => e.Ymd).HasComment("計画有給年月日");
            entity.Property(e => e.YukyuKeikakuId).HasComment("計画有給ID");

            entity.HasOne(d => d.YukyuKeikaku).WithMany(p => p.YukyuKeikakuMeisais)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yukyu_keikaku_meisais_fk1");
        });

        modelBuilder.Entity<YukyuNendo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("yukyu_nendos_pkc");

            entity.ToTable("yukyu_nendos", tb => tb.HasComment("有給年度"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.EndDate).HasComment("終了日");
            entity.Property(e => e.IsThisYear).HasComment("今年度フラグ");
            entity.Property(e => e.Nendo).HasComment("年度");
            entity.Property(e => e.StartDate).HasComment("開始日");
            entity.Property(e => e.Updated).HasComment("更新フラグ");
        });

        modelBuilder.Entity<YukyuRireki>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("yukyu_rirekis_pkc");

            entity.ToTable("yukyu_rirekis", tb => tb.HasComment("有給履歴"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.HannitiKaisuu).HasComment("半日有給取得数");
            entity.Property(e => e.KeikakuTokukyuSu).HasComment("計画特休数");
            entity.Property(e => e.KeikakuYukyuSu).HasComment("計画有給数");
            entity.Property(e => e.Kurikoshi).HasComment("繰越日数");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.Syouka).HasComment("消化日数");
            entity.Property(e => e.Wariate).HasComment("有給日数");
            entity.Property(e => e.YukyuNendoId).HasComment("有給年度ID");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.YukyuRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yukyu_rirekis_fk2");

            entity.HasOne(d => d.YukyuNendo).WithMany(p => p.YukyuRirekis)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yukyu_rirekis_fk1");
        });

        modelBuilder.Entity<YuukyuuZan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("yuukyuu_zans_pkc");

            entity.ToTable("yuukyuu_zans", tb => tb.HasComment("有給残日数"));

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.HannitiKaisuu).HasComment("半日有給取得数");
            entity.Property(e => e.KeikakuTokukyuSu).HasComment("計画特休数");
            entity.Property(e => e.KeikakuYukyuSu).HasComment("計画有給数");
            entity.Property(e => e.Kurikoshi).HasComment("繰越日数");
            entity.Property(e => e.SyainBaseId).HasComment("社員BaseID");
            entity.Property(e => e.Syouka).HasComment("消化日数");
            entity.Property(e => e.Wariate).HasComment("有給日数");

            entity.HasOne(d => d.SyainBase).WithMany(p => p.YuukyuuZans)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("yuukyuu_zans_fk1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}